### ISSUE TITLE
[FEAT] A small rework of the toolbar

### ISSUE THREAD

**Issue by 45i** [eythaann/Seelen-UI#100]
- Instead of opening the battery settings when the battery icon is pressed, open a small flyout which will be the alternative to the windows action menu (Win+A). The flyout might contain things like brightness slider, battery percentage, volume slider, buttons for bluetooth, wifi, hotspot and so on. 
- Similarly, instead of opening the bluetooth settings when clicking bluetooth icon, open a flyout containing available bluetooth devices (much like the wifi flyout). 
- Clicking on the notification icon, yes, does show the notifications, but clicking on them does nothing and when there's no notifications, the flyout shouldn't be THIS big and especially not contain the clear all notifications button.
![image](https://github.com/user-attachments/assets/3954f90d-5fb2-4d9e-9fae-b17767f9fa97)

PS: an alternative to point 1 might be to have the flyout on the quick settings flyout, which looks rather dry rn
![image](https://github.com/user-attachments/assets/8beda540-7470-44e6-9994-a830106e5890)

**Comment by 45i** [comment]
> download
> 
> https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
> 
> you may need to install the c compiler

sorry?

**Comment by 45i** [comment]
also heres something interesting i just realised, every flyout is a dark grayish color, EXCEPT for the the notification flyout which for some reason is light gray?

**Comment by eythaann** [comment]
duplicated of #61
