### ISSUE TITLE
[BUG] Locking the computer closes Seelen-UI

### ISSUE THREAD

**Issue by anthonymendez** [eythaann/Seelen-UI#102]
**Describe the bug**
Everytime I lock my computer for sometime, then come back to unlock, Seelen-UI isn't running anymore and I have to relaunch it. My computer doesn't have sleep enabled if away for some time. The screen does shutoff however.

**To Reproduce**
1. Launch Seelen-UI.
2. Lock the computer with `Windows-Key+L`.
3. Leave the computer long enough for the monitors to shut off.
4. Come back to the computer and unlock.
5. See regular windows taskbar instead.

**Expected behavior**
Seelen-UI should be the taskbar.

**Comment by ljbred08** [comment]
Same problem. Pretty frusturating.
