### ISSUE TITLE
[BUG] Seelen UI doesn't work on LTSC 21H2

### ISSUE THREAD

**Issue by u216** [eythaann/Seelen-UI#103]
**Describe the bug**
After installing, Seelen UI doesn't work at all, you can go into the setting ui but anything else doesnt work. I have a LTSC 21H2 JP installed.

Using 2.0.0 Beta 7, x64

Restarting doesnt work
I had Edge uninstalled but installed it again.
**To Reproduce**
1. Install Seelen UI on LTSC 21H2 Japanese

**Expected behavior**
The program works, it runs, but it doesn't have its UI show up.

**Comment by eythaann** [comment]
Yes I take in care that new versions are not working on windows 10. This will be fixed before launch the final v2 release.

**Comment by eythaann** [comment]
fixed on 9b09dd6fe8e95fae59aaa8f9b24019bf652e0b8f (deployed on beta.14)
