### ISSUE TITLE
[BUG] Toolbar is only showing up on one monitor

### ISSUE THREAD

**Issue by CodKid1710** [eythaann/Seelen-UI#105]
The Toolbar is only showing up on one monitor

I don't know what exactly i did, but the toolbar is only showing up on one monitor (My external monitor)

I have fancy Toolbar enabled and i changed the Toolbar structure to Default-Alter (i tried default)
My toolbar height is the default 30 and auto hide is never

My virtual desktop strategy is Seelen, but i also tried native
Tiling window manager is off

I have tried having one and two monitors in the monitor tab (then clicking save) with all the default options and still i only get the taskbar on my external monitor (I have a laptop)

my Seelen UI version is v2.0.0-beta.8

I am pretty sure that i am supposed to see a taskbar on both monitors

if anyone knows the problem or what settings i need to change thank you! :)

**Comment by Alfiejz** [comment]
Just installed v2.0.0-beta.8 on windows 11, same issue here.
Toolbar/taskbar only appearing on secondary monitor and not primary. Monitors tab only shows my 2nd monitor.

**Comment by eythaann** [comment]
please, send me your log files `C:\Users\{your user}\AppData\Local\com.seelen.seelen-ui\logs`

**Comment by eythaann** [comment]
probably the app is been hidden by a fake detection of full screen app on one monitor

**Comment by CodKid1710** [comment]
[Seelen UI.log](https://github.com/user-attachments/files/17158143/Seelen.UI.log)

Here is the file.

i think the issue is line 305

Hope this helps

Thank you in advance

**Comment by eythaann** [comment]
@CodKid1710 try beta 14 and tell me if this is still happening, otherwise close this issue as  @completed.

**Comment by CodKid1710** [comment]
thanks it works now, loving seelen so far, keep up the work
