### ISSUE TITLE
[BUG] Taskbar does not reappearing when autohide is set to On-Overlap

### ISSUE THREAD

**Issue by CarlosAllberto** [eythaann/Seelen-UI#106]
Replicable:
* enable autohide on overlap
* overlap the dock
* close/minimize the window overlapping the dock

**Comment by eythaann** [comment]
... I need exactly what program, or all programs on fullscreen, an image, more details please.

**Comment by CarlosAllberto** [comment]
I will send you a video on discord showing the bug

**Comment by eythaann** [comment]
already fixed on v2
