### ISSUE TITLE
[FEAT] Better Auto Hide 

### ISSUE THREAD

**Issue by CodKid1710** [eythaann/Seelen-UI#107]
If you turn "Auto Hide" to "Never" you get a HUGE gap at the bottom of your screen where you can see a little bit of the background

It would be nice if changing this setting to "Never" just overlayed the taskbar on top of the application.
Cause the huge gap kinda destroys the vibe :(

Thanks, overall i like Seelen UI, just a little buggy. :)

LOOK AT THIS
![THICCbezel](https://github.com/user-attachments/assets/5a6e5e85-31dc-485f-81bc-9e7ba60f0c53)

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo

Password: changeme

you may need to install the c compiler

**Comment by eythaann** [comment]
ehmmm if the dock is "always" on top aplications, how will you click thought to it?
