### ISSUE TITLE
[BUG] If the “Country and region” in the regional settings does not match the “Regional format” (the country does not match), the application will not work properly.

### ISSUE THREAD

**Issue by fallenleave0620** [eythaann/Seelen-UI#110]
##**Describe the bug**
 ###**I accidentally discovered that if the “Country and Region” and “Region Format” in the Regional Settings are not the same (Country is not the same), the application will not work correctly, and the taskbar and toolbar will not be displayed correctly and can not be operated.**

**Comment by eythaann** [comment]
can you share the log files when the app fails after changing the region please?

**Comment by fallenleave0620** [comment]
[Seelen UI.log](https://github.com/user-attachments/files/17220721/Seelen.UI.log)

**Comment by fallenleave0620** [comment]
Another issue is that when I reboot or log off the computer, the taskbar and toolbar don't show up unless I toggle the Native/Seelen option, save the settings and reboot, then they show up!

**Comment by fallenleave0620** [comment]
Maybe it has something to do with issue#111

**Comment by eythaann** [comment]
hmmmm I don't see any important error, just one on the toolbar, related with a breaking change in the types that I do, but the logs looks fine, what exactly happens after changing the region?

**Comment by fallenleave0620** [comment]
I'm not sure if it's triggered by the language settings, but I have a log here that some of the buttons on the toolbar are often in an unavailable state, e.g., Open System Tray, Bluetooth & Devices, Device Power, and these are the only ones I've found
[Seelen UI.log](https://github.com/user-attachments/files/17221302/Seelen.UI.log)

**Comment by eythaann** [comment]
try changing the layout of the toolbar on settings to another one than custom and check again.

**Comment by fallenleave0620** [comment]
The problem remains.
[Seelen UI.log](https://github.com/user-attachments/files/17221380/Seelen.UI.log)

**Comment by fallenleave0620** [comment]
[Seelen UI.log](https://github.com/user-attachments/files/17221552/Seelen.UI.log)

**Comment by eythaann** [comment]
> [Seelen UI.log](https://github.com/user-attachments/files/17221552/Seelen.UI.log)
> 

ohh now it shows errors, there's one related with failed tray overflow creation, and the others well idk what exactly the error says, but I will check all these in some hours.

**Comment by fallenleave0620** [comment]
https://github.com/user-attachments/assets/001f7e61-e128-4c43-b9d8-ab8a5d968a43

**Comment by eythaann** [comment]
only shit, I see now I know what is happening, thanks for the advice.

**Comment by eythaann** [comment]
@fallenleave0620 I see you're using beta.5 please try lastest versions the tray had recieved many fixes.

**Comment by eythaann** [comment]
@fallenleave0620 try beta 14 and if all is ok close this issue as completed.
