### ISSUE TITLE
[BUG] the taskbar and toolbar don't show up

### ISSUE THREAD

**Issue by fallenleave0620** [eythaann/Seelen-UI#111]
**Describe the bug**
Another issue is that when I reboot or log off the computer, the taskbar and toolbar don't show up unless I toggle the Native/Seelen option, save the settings and reboot, then they show up!

**To Reproduce**
1. restart or log off the computer
2. the taskbar and toolbar are not displayed
3. switch the Native/Seelen option and save the setting
4. restart the software
5. it can display

[Seelen UI.log](https://github.com/user-attachments/files/17220818/Seelen.UI.log)

**Comment by fallenleave0620** [comment]
Only one Seelen process in the task manager
![image](https://github.com/user-attachments/assets/2c0f1b0d-19f4-4e82-a1dd-9b0b3cdc57b3)

**Comment by fallenleave0620** [comment]
[Seelen UI.log](https://github.com/user-attachments/files/17221179/Seelen.UI.log)

**Comment by eythaann** [comment]
this is already reported, the startup sometimes not work correctly because, well is a system thing that I has to wait for it before start the program. I will fix this soon.

**Comment by eythaann** [comment]
#57
