### ISSUE TITLE
[BUG] programs appear in the taskbar even when their window is closed

### ISSUE THREAD

**Issue by 3101-Gunner** [eythaann/Seelen-UI#116]
some programs (specifically those that run in the background such as steam and discord) will appear open in the taskbar, even if their  window is closed
ive also had times where stuff like bakkesmod and windows media player will do the same thing

to reproduce,
open steam
close all steam windows, but keep steam running in the background

expected behavior: taskbar shows no program as open

![image](https://github.com/user-attachments/assets/975906e2-ace2-4ccb-8369-5421417285d4)
(when alt tabbing, no steam window is shown)

**Comment by eythaann** [comment]
Like it is a little hard to replicate to me, I just add some preventive code, so idk if that commit will fix this issue.
Please test the next beta 16 and tell me if this issue persist reopening this ticket.
