### ISSUE TITLE
[Toolbar - Open System Tray - BUG]

### ISSUE THREAD

**Issue by rafliiar17** [eythaann/Seelen-UI#117]
**Describe the bug**
When i clik 3 dot on open system tray its not showing (reload the seelen) but the view become untidy

**To Reproduce**
1. Click on 'Open System Tray'
2. See error

i using https://github.com/eythaann/Seelen-UI/releases/tag/v2.0.0-beta.15 this version

![image](https://github.com/user-attachments/assets/cd3f73c6-71bb-4c0e-80ac-39f031eedd13)

**Comment by PhantomPixel-0418** [comment]
#95 was not successfully resolved
