### ISSUE TITLE
[BUG] Toolbar

### ISSUE THREAD

**Issue by CarlosAllberto** [eythaann/Seelen-UI#119]
When Semen is run for the first time or the computer is restarted the toolbar appears with a negative top margin.

It is fixed by disabling and enabling the taskbar or changing default mode to default-alter.

![Captura de tela 2024-10-07 145455](https://github.com/user-attachments/assets/d600f717-43c1-409b-9b7e-598427fbb54f)

**Comment by eythaann** [comment]
I really don't have fucking idea why this sometimes happen, it's like Windows by itseft moving the UI window of place. btw I could just ensure the position after some seconds of startup and sleep up.
