### ISSUE TITLE
[BUG] Full-screen start menu is bugged

### ISSUE THREAD

**Issue by ThePixelDude111** [eythaann/Seelen-UI#131]
I have windows 10 22h2, and I have the latest beta version of seelen-ui installed, and full screen menu isn't...full-screen.

Here is a screenshot:
![Screenshot (21)](https://github.com/user-attachments/assets/6e28e417-d592-4fb7-af73-caf817c78e3f)

**Comment by eythaann** [comment]
hmmmm I suppose the dock is in solid mode (auto-hide: never) right?

**Comment by ThePixelDude111** [comment]
> hmmmm I suppose the dock is in solid mode (auto-hide: never) right?

No, it is set to auto-hide on overlap

**Comment by ThePixelDude111** [comment]
I believe that a part of the problem isn't from the app itself, as when I close it and open the start menu, it still doesn't fill the screen (maybe because I have rectify 11 installed), but the dock's space is still reserved in the app

**Comment by eythaann** [comment]
the dock only reserve space when auto hide is never. so I think this is not related with Seelen UI. btw testing on win 10 is a little poor so any is possible.
