### ISSUE TITLE
[FEAT] "Pin" subcategory more recognizable

### ISSUE THREAD

**Issue by MyDrift-user** [eythaann/Seelen-UI#141]
**Is your feature request related to a problem? Please describe.**
I did click on "Pin" for an application on a dock, but it did not pin.
sometimes later I fount out that it has a subcategory that shows if you stay hovered on "Pin".
![Screenshot 2024-10-13 100703](https://github.com/user-attachments/assets/d4e13feb-d991-4a14-9a12-5e541438c6a3)

**Describe the solution you'd like**

1. Provide an indicator, that there is more to it:
![Screenshot 2024-10-13 100703](https://github.com/user-attachments/assets/61a6dcc4-bd02-4526-be68-d20ef1632dfd)

2. Provide a "Default" selection if you click on "Pin" alone. Default would most likely be to the Center I think.

**Comment by eythaann** [comment]
I will revome sub categories and just leave Pin and it should work as "pin in place", pin on sides was before made the items draggable.

**Comment by eythaann** [comment]
Submenu removed on v2.0.13
