### ISSUE TITLE
[BUG] Media Module should not appear if no media is playing 

### ISSUE THREAD

**Issue by notNSANE** [eythaann/Seelen-UI#145]
**Describe the bug**
Media Module should not appear if no media is playing

**To Reproduce**
1. Don't start any media

**Expected behavior**
Media Module should not appear if no media is playing.

I'll add a note here on why:

Media Module is amazing but if no media is being played it's just there doing nothing. What's worse, buttons appear to work when clicked, but they don't do anything because again, no media is played.

If nothing can be done about this for now because there's no code to hide a module temporally (or requires significant work), I suggest at least making the buttons have no animation or cursor change until media is played.

**Comment by eythaann** [comment]
as edge case imagine this: media is hidden, but it is still on that position, If I move some items the media module will be also moved and user will have no idea until media module pop up.

**Comment by eythaann** [comment]
so the second workaround is a better fit I think, I will take this ticket to work only on that. If you find some concept/design idea of how should look the media module when no media is playing it would be nice.

Also as note: other media music player when no playing shows a empty media player with and empty album image.

**Comment by notNSANE** [comment]
> as edge case imagine this: media is hidden, but it is still on that position, If I move some items the media module will be also moved and user will have no idea until media module pop up. User: why my media module is now on center of the dock???

ahhh, this is tricky, I haven't considered this! The app is so extremely customizable I completely missed I could do this.

In that case... what about showing this? 

![image](https://github.com/user-attachments/assets/a66a140b-6c22-4751-a5f7-3333c418bf3d)

Worst mockup in history, but if it's possible, show just the icon without the controls and no media text. It even could be something cooler like showing the icon without the vinyl because there's no media being played. Then, when media is played, the vinyl appears and the rest of the controls too. This solution still doesn't solve what does the icon/feature means on the first start of the software, but I guess it's a good start.

**Comment by eythaann** [comment]
I think that showing the vinyl only is more confuse than showing the no media text.

**Comment by eythaann** [comment]
YoutubeMusic:
![image](https://github.com/user-attachments/assets/b81e62df-bd3c-4fd6-99be-253b2dd76cd0)
