### ISSUE TITLE
[FEAT] The Wall should include an "Add folder" option to add many images at once

### ISSUE THREAD

**Issue by notNSANE** [eythaann/Seelen-UI#147]
**Is your feature request related to a problem? Please describe.**
I have to manually add hundreds of images manually.

**Describe the solution you'd like**
Just an add folder button. After added, Seelen UI should scrape the entire folder and add all the images.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by eythaann** [comment]
currently you can select multiple files when adding backgrounds.
