### ISSUE TITLE
[FEAT] Add minutes and days to time to change wallpapers on The Wall

### ISSUE THREAD

**Issue by notNSANE** [eythaann/Seelen-UI#149]
**Is your feature request related to a problem? Please describe.**
I normally switch wallpapers every day, I shouldn't have to do a calculation to find out how many seconds are there in a day. 

**Describe the solution you'd like**
Hard to choose my favorite solution, but I'm all about options. Perhaps something like this?

`Switch wallpapers every                                   Days [ _______0 ] Minutes [ _______0 ] Seconds [ _______0 ]`

This way the user can add the numbers they want and switch wallpapers... in any way they want.

**Describe alternatives you've considered**
-

**Additional context**
Pretty sure this is planned but I'll add the bug anyways 😁 Very minor issue tho.

**Comment by eythaann** [comment]
yes but you has to take in consideration that it will only apply if you never shutdown the pc or update the app after an update or restart the counter will start from 0 again, so for days I thought its better a option called "select random wallpaper on start" or something like that, what do you think?

**Comment by notNSANE** [comment]
Isn't there an elegant code solution to this? Obviously you can't check/write a file every single second to see if something changed regarding this... 
Hm.

Let's split the issue -- first: _Select random wallpaper on start_, yes. That should exist anyways and it's a great option to have.

Now... if the user restarts the PC -- Well, you have write the number somewhere in settings, I don't understand why Seelen can't write/check that number somewhere every... say, 10 minutes minimum? Personally I think changing a Wallpaper every less than 30 minutes will be just too annoying but can't speak for everyone. 
If so, then you offer the option to change every X minutes, with a minimum of 10 minutes.

Microsoft's "spotlight" feature is every 1 minute. But I guess it's been tested and optimized to hell by several engineers.

**Comment by eythaann** [comment]
spotlight is like the randomize I told, but on a bunch of thousands of images.

**Comment by eythaann** [comment]
![Seelen UI Wallpaper Manager](https://github.com/user-attachments/assets/cc5396b6-e991-430d-9861-028a8e0906b4)
