### ISSUE TITLE
[BUG]Can not connect WIFI by clicking network indicator on bar

### ISSUE THREAD

**Issue by jackjxx** [eythaann/Seelen-UI#154]
Click the Wi-Fi icon on the taskbar to select the corresponding Wi-Fi link, but it can't connect。 Also cannot switch to other Wi-Fi hot point!!!

![image](https://github.com/user-attachments/assets/06e93767-4850-4ba3-86ba-16a8ffa3bee6)

**Comment by eythaann** [comment]
sometimes after click connect just has to wait and the network will be connected but the the button still will say connect, if you click it again it will disconnect/or trying to connect again.

**Comment by korepunk** [comment]
The WiFi issue is more than just waiting and being patient. It doesn't even provide me with the option to input the password.
