### ISSUE TITLE
[BUG] Dock on mutiple monitors is not in sync.

### ISSUE THREAD

**Issue by MyDrift-user** [eythaann/Seelen-UI#158]
**Describe the bug**
I have two monitors, but on my secondary one the dock is not updating correctly. I suddenly have the same window open 3 times and pinned an additional time. But in reality I do not even have the pinned app opened, which the Dock on the first Window shows correctly.
The non existing opened appitems do not have an app preview at all (does not show up).
Rightclicking the "ghost" appitems just does the animation of clicking it, but does not actually do anything.

**Screenshots**
Monitor 1:
![image](https://github.com/user-attachments/assets/13a7c6fb-6958-4679-8bc8-704156cb6525)

Monitor 2:
![image](https://github.com/user-attachments/assets/5d1a1036-9db7-46c1-b60a-9237ead82223)
![image](https://github.com/user-attachments/assets/1e9453d2-f3af-4caf-8bcc-67d3d8d97c3e)

Also trying to move the appitems in this state breaks everything you've sorted (btw I've only moved MS Teams more to the left, and now it looks like this on the second dock. The primary Dock is still fine):
![image](https://github.com/user-attachments/assets/a2542274-ad1b-4d5e-b52d-4ebcb56958ee)

**Comment by eythaann** [comment]
yeah this will be solved on v2.1 I'm moving the state from instances to a single state for all windows on the background

**Comment by eythaann** [comment]
someone could test this on latest nightly, please?

**Comment by eythaann** [comment]
fixed on v2.0.13
