### ISSUE TITLE
[BUG] Can't remove media module on dock

### ISSUE THREAD

**Issue by Luwo-bit** [eythaann/Seelen-UI#16]
**Describe the bug**
After right clicking the dock to add a media module, right clicking again does not allow me to remove media module

**To Reproduce**
1. Install SeelenUI
2. Right click dock
3. Click "Add Media Module"
4. Right click dock again, it will say "Add Media Module" and clicking does not remove the module

Another thing to note is that after uninstalling and reinstalling, all my preferences are still there, including pinned apps and the media module. I've tried going through and deleting files from SeelenUI elsewhere on my computer (only found one folder in AppData\Roaming called com.seelen.seelen-ui) but the preferences still persist.

**Screenshots**
![image](https://github.com/user-attachments/assets/43b8fcc6-e59a-4b81-930e-a3973cd2caf3)

**Comment by eythaann** [comment]
On cae59f92a0decf4ace5b5a7cb6c4ecc9c833df47 a delete data checkbox was added to delete all the application data. this will be released on v1.8.3.

![image](https://github.com/user-attachments/assets/68ce189a-c61e-4ff5-a4b2-b3f5d43cd920)
