### ISSUE TITLE
[FEAT] Show calendar when press Time/Date 

### ISSUE THREAD

**Issue by milen-prg** [eythaann/Seelen-UI#160]
Show the calendar when press/click on Time/Date as in the standard Windows 11 taskbar.

**Comment by luriusTM** [comment]
Let's check back, what is exactly needed.

Does this satisfy the basic need, or what features do you feel apropriate for this view? 
![image](https://github.com/user-attachments/assets/9439520a-7081-425b-868a-5ee75ae84151)

**Comment by milen-prg** [comment]
@luriusTM how to show this calendar? The click on the date not work.

**Comment by luriusTM** [comment]
Not yet accessible. That is why I asked, what else do you need. If this is satisfies the expectations, then I will make a PR for it.

**Comment by milen-prg** [comment]
> Not yet accessible. That is why I asked, what else do you need. If this is satisfies the expectations, then I will make a PR for it.

Thank, you! This will be excellent.
