### ISSUE TITLE
[BUG] Windows arm architecture compatibility.

### ISSUE THREAD

**Issue by rexxDZN** [eythaann/Seelen-UI#165]
**Describe the bug**
Please create a windows arm version. This will help the app run (smoothly) and use less battery life.

**Comment by eythaann** [comment]
there is a arm version but is still on testing stage.

**Comment by eythaann** [comment]
This will be performed but is not a bug, so I will close this issue.

**Comment by rexxDZN** [comment]
> there is a arm version but is still on testing stage.

Do u have any update on this? i'd love to try it out

**Comment by eythaann** [comment]
not yet.
