### ISSUE TITLE
[BUG] Preview Application Window background scrolling not overflowing screen edge

### ISSUE THREAD

**Issue by ITMonkey78** [eythaann/Seelen-UI#169]
**Describe the bug**
When you have many windows open for one app the Preview windows overflow past the monitors edge but the background does not.
Scrolling to the right shows the offscreen Preview windows but the Preview background also scrolls so background becomes transparent

**To Reproduce**
Open multiple Browser Windows (windows not tabs) - at least 8 to cause the Preview window overflow
Select the Preview bar to bring it to focus
scroll left/right with mouse drag or arrow keys

**Expected behavior**
Background should overflow with the Preview windows to entire length or remain static to screen width.

**Screenshots**
![image](https://github.com/user-attachments/assets/fdb26efa-0f29-4025-a545-5d570b9557eb)

![image](https://github.com/user-attachments/assets/66bc38a7-5a36-4e1f-9d58-383f4c4e6aea)

Native Windows Application Preview reduces the size of the thumbnail images to allow them all to fit onscreen without scrolling so that could be a solution. Or add < > scrollers to the Preview Thumbnail display for easier scrolling?

**Comment by eythaann** [comment]
haha lol, thanks for the report I never test this so.
