### ISSUE TITLE
[BUG] Screen overlay display error

### ISSUE THREAD

**Issue by NDKcute** [eythaann/Seelen-UI#170]
This error occurs when I open the app, and it shows an overlay on the screen and makes me unable to see anything behind it.
I think it's a bug that causes the overlay to not be completely hidden, which is causing the error.
I am a windows insider of canary version

![image](https://github.com/user-attachments/assets/d4e69c97-0725-4280-b404-94230b10b7e6)

**Comment by eythaann** [comment]
you has to update your windows and webview runtime versions to the lastest ones.

**Comment by eythaann** [comment]
https://discord.com/channels/751144791596597561/1297374679014703164
