### ISSUE TITLE
Unable to start windows

### ISSUE THREAD

**Issue by HungHHong** [eythaann/Seelen-UI#171]
**Describe the bug**
After installed V2.0.3 and set program to auto-run on start up, after restart device stuck in an endless loop where windows is unable to initialized the application and screen keep flashing every 2 second. Unable to do anything else, can't end application in task manager since no application start yet. I have to do an restore point 

**To Reproduce**
1. install V2.0.3
2. Set auto run on start
3. restart device
4. Unable to start windows

**Comment by ParthdJindal** [comment]
I have the same issue. even after run on start is set on its turns back off itself if the app is relaunched or device is restarted

**Comment by Atlantis-Gura** [comment]
The same issue persists in version 2.0.5

**Comment by HungHHong** [comment]
> The same issue persists in version 2.0.5, and it still exists even after uninstallation, I don't know how to fix it.

What I have to do is that I got to do an windows recovery, and go back to the last restore point, (Hopefully you have something recent)
Or 
try to delete it in safe mode
Or 
try to uninstall using CMD [Here](https://www.howtogeek.com/702540/how-to-uninstall-a-program-on-windows-10-from-command-prompt/)

**Comment by eythaann** [comment]
please send me your log files inmediatly after the crash, to debug the issue.

**Comment by HungHHong** [comment]
> please send me your log files inmediatly after the crash, to debug the issue.

Unfortunately it render my Laptop Useless, since there is nothing from windows is pop up. I wish coulda record the screen or something. But essentially after Install everything seem to work fine. However after the first reboot, the screen keep flashing black after get into windows. Everything render useless, Win+R bring up the command, however it would disappear after the screen flash.

**Comment by eythaann** [comment]
@HungHHong could you try last version to see if it works now?
