### ISSUE TITLE
[FEAT] Include AppData\Roaming Directories in Windows Store Install

### ISSUE THREAD

**Issue by LokenCerberus** [eythaann/Seelen-UI#176]
Editing Placeholder YAML files in the Windows Store install location is dangerous, and when installed from the Windows Store Seelen UI does not create the folder structure under "C:\Users{USER}\AppData\Roaming\" required for customization.

Solution: Windows Store installed Seelen UI Creates "com.seelen.seelen.ui" folder structure automatically under "C:\Users{USER}\AppData\Roaming\"

**Comment by eythaann** [comment]
This is a feature of MSIX or UWP, basically it stores all the data created by the app to be easier to clean after an uninstallation, so this is intended.
