### ISSUE TITLE
[BUG] Hide on Overlap Dual Monitor issue

### ISSUE THREAD

**Issue by Vehlore** [eythaann/Seelen-UI#178]
**Describe the bug**

When using more than one monitor, having the Hide on Overlap function active and focusing on an window on the secondary monitor will stop the UI on the main monitor from hiding.

Note: I have the main monitor configuration set to Hide on Overlap and the secondary monitor set to Always hidden.

**To Reproduce**

1. Activate Hide on Overlap function in Seelen UI settings for dock and toolbar.
2. Open a two windows/applications, one on each monitor, both maximized.
3. Focus (click) on the window in the main monitor and make sure the UI hides.
4. Focus (click) on the window in the second monitor and see the UI in the main screen come back.

**Expected behavior**

For my understanding/preference, the main monitor should still have the UI hidden while the windows in it are maximized even if they are not the focused on. 

**Screenshots**

![image](https://github.com/user-attachments/assets/2f38736e-c5bf-490a-902e-bda7a53c38ca)

**Comment by eythaann** [comment]
This is intended, "overlap" means hide if the active window is overlapping with the dock/topbar when you click the second monitor the app is not overlapping the dock on the other monitor so this is working fine.

**Comment by eythaann** [comment]
btw, adding a option called, persist last focus on monitor could be a good option.

**Comment by Vehlore** [comment]
> btw, adding a option called, persist last focus on monitor could be a good option.

I would like to see this as an option.

**Comment by eythaann** [comment]
This is already an option on Dock and Toolbar settings.

![image](https://github.com/user-attachments/assets/f8ce3723-57da-49b4-ba4c-15e7e5b90ec9)
