### ISSUE TITLE
[BUG] Full screen apps need two clicks to reopen

### ISSUE THREAD

**Issue by Vehlore** [eythaann/Seelen-UI#179]
**Describe the bug**

When having an app on full screen mode (i.e. a game or a full screen video on YT), if switching apps and wanting to come to the full screen application, it needs to be clicked twice to open again.

**To Reproduce**

1. Open any full screen app, either a video or a game. I tried full screen YT video and League of Legends.
2. Alt+Tab to change to another window or the desktop.
3. Try to click on the app again to come back to it and it won't open on the first click.

**Expected behavior**

After alt+tab, wanting to come app to the full screen application should only need one click.

**Screenshots**

Unable to provide screenshot.

**Comment by Vehlore** [comment]
I also found out it happens sometimes with non full screen apps but I'm unable to replicate it. I'll try to figure out what's happening or take a video of it and send it here.

**Comment by eythaann** [comment]
I think this is related with the workspaces feature, but let me know more info about this if you can.

**Comment by Vehlore** [comment]
> I think this is related with the workspaces feature, but let me know more info about this if you can.

I'll upload a video about it so you can have a more visual explanation of the issue. Give me a few hours =)

**Comment by Vehlore** [comment]
@eythaann here's the video showing the behavior of the apps in full screen and some others needing double click to open.

https://github.com/user-attachments/assets/c90de048-49f0-43c0-8649-365c96e51509

As you can see, when clicking on the full screen application from the desktop, it will need to be clicked again for opening. 

As for the Discord, I'm not sure if that specific window is being detected as full screen or not but you see the behavior is the same as with League of Legends.
