### ISSUE TITLE
[FEAT] Option to overlap dock without hiding it

### ISSUE THREAD

**Issue by Vehlore** [eythaann/Seelen-UI#181]
**Is your feature request related to a problem? Please describe.**

It would be nice to have an option for the dock to overlap on top of the full window without hiding, even taking a bit of space in the active window.

**Describe the solution you'd like**

Allow the dock to sit on top of the window.

**Additional context**

![image](https://github.com/user-attachments/assets/3db10c5f-f53e-4d24-9263-c60c3513e426)

Just like shown in this screen.

**Comment by eythaann** [comment]
this will avoid clicking on the app and looks more like a bug. For this you can use autohide: never, that will works as a solid taskbar.
