### ISSUE TITLE
[BUG] System tray not opening some apps

### ISSUE THREAD

**Issue by Vehlore** [eythaann/Seelen-UI#182]
**Describe the bug**

When double clicking some apps on the system tray they won't open.

Two apps I found not working properly, Steam, when clicking it will only open the secondary menu. The Riot launcher will not even open anything and just stay there with the app tag.

**To Reproduce**

1. Go to System Tray
2. Double click on some apps to test
3. See if the apps open or behave otherwise

**Expected behavior**

Apps should open on double click like intended.

**Screenshots**

![image](https://github.com/user-attachments/assets/4f1c6b27-38c0-45c7-9ed4-1493a00967b3)

When double clicking Riot Client 

![image](https://github.com/user-attachments/assets/02f2e28c-7786-4774-9be3-463627f6cff2)

When clicking Steam

![image](https://github.com/user-attachments/assets/78da13ce-a6ff-4d97-ad18-5f9b325fab06)

**Comment by eythaann** [comment]
I don't remember the issue but this is a duplicated and double click is not supported, and it can't be implemented.
