### ISSUE TITLE
Task manager not showing when open in dock

### ISSUE THREAD

**Issue by Joshua-Nweze** [eythaann/Seelen-UI#184]
the task manager does not show in the dock when it's open.
even after i pinned the task manager to the dock, and it's open it won't indicate in the dock, it will be as if it's not open
![Screenshot 2024-10-19 105407](https://github.com/user-attachments/assets/71698cb5-3d00-48da-aa7f-faac24d1373c)

**Comment by Vehlore** [comment]
Tested and confirmed, for me it even doesn't show in the dock LOL

![image](https://github.com/user-attachments/assets/9675026d-7ddc-44ad-af55-67964f04bab7)

**Comment by eythaann** [comment]
you need run Seelen UI as admin.

**Comment by Joshua-Nweze** [comment]
okay 👍🏽
