### ISSUE TITLE
[BUG] No permissions?

### ISSUE THREAD

**Issue by skyisthela** [eythaann/Seelen-UI#187]
**Describe the bug**
Upon trying to edit the yaml/yml files in static folder I get this error
![{F8404DCC-760D-4908-AF53-AD530FBFD608}](https://github.com/user-attachments/assets/7aa19c35-264d-45a3-858f-594597073be0)
However the files in AppData allows editing, but there is only a single custom.yml file and even if I copy them into the roaming folder nothing happens.

**To Reproduce**
1. Go to Seelen-UI folder > static folder > placeholders folder > any yml file
2. Edit said files
3. Get pop up

**Expected behavior**
Allow changes

**Comment by eythaann** [comment]
Program Data Folder, is only editable via admin right this is native of windows, and also you shouldn't edit files in the installer folder. copy the placeholder into you appdata user folder and edit it in that place as a new placeholder.
