### ISSUE TITLE
[BUG] Taskbar and dock bar at the same time

### ISSUE THREAD

**Issue by PhantomPixel-0418** [eythaann/Seelen-UI#188]
**Describe the bug**
Taskbar and dock bar at the same time

**To Reproduce**
1. Turn off auto-hide taskbar
2. Open Seelen UI
3. See error

**Expected behavior**
Show Dock Bar Only

**Screenshots**
![image](https://github.com/user-attachments/assets/6757b4ac-8058-40b0-99a6-d15f8f3d5398)

**Comment by eythaann** [comment]
Well the taskbar is hidden on start of the app, so just restarting the seelen ui app will hidde the taskbar again, so I will close this like is the user who trigger this from native Windows Settings.
