### ISSUE TITLE
Dock displaying only the active windows for each virtual desktop and monitor

### ISSUE THREAD

**Issue by grohmaaan** [eythaann/Seelen-UI#192]
Add an optional feature to the dock that mimics Windows taskbar behavior, where only the active windows are shown on the dock for each virtual desktop and monitor. Similar to the Windows setting where the taskbar only displays apps on the monitor where the window is open (see screenshot), this feature should ensure that virtual desktops always show only active windows on their respective desktops.

![image](https://github.com/user-attachments/assets/5a8efdb3-b3c7-413e-9221-5324010a8224)

**Comment by k-gaia** [comment]
Came here to make this same request, adding a comment to emphasise how much I'd love this - it'd be perfection on an already perfect package

**Comment by eythaann** [comment]
closed in favor of: #271
