### ISSUE TITLE
[FEAT] I only need to be able to position the Windows Taskbar vertically

### ISSUE THREAD

**Issue by knowbits** [eythaann/Seelen-UI#194]
I am looking for a utility that allows me position the Windows Taskbar vertically. 

The "Dock bar" looses too many useful features for my use, so I would like to keep the Windows Taskbar as is, if possible. 

It would be great to have an option to keep the Taskbar, but to be able to relocate it to the right side of the screen.

**Comment by eythaann** [comment]
There's other tools for that, Seelen UI doesn't modify the native system so this is unplanned.
