### ISSUE TITLE
[BUG] Cannot open systems applications

### ISSUE THREAD

**Issue by lycis** [eythaann/Seelen-UI#203]
**Describe the bug**
When having Seelen UI active I cannot open (some) system applications, such as "work or school account", requiring me to disable the UI whenever I want to do so

**To Reproduce**
1. Search app "work or school account"
2. Open it
3. Nothing happens

**Expected behavior**
The UI should not interfere with opening any applications.

**Screenshots**
-

**Comment by eythaann** [comment]
I currently can open Teams normally, so I will close this.
