### ISSUE TITLE
[FEAT] Open Calendar

### ISSUE THREAD

**Issue by Biliskn3r** [eythaann/Seelen-UI#210]
Hello, any way to add the Windows Calendar to open when you click the date/time like on the "normal" taskbar?

Looking good so far and very usable.

**Comment by luriusTM** [comment]
Let's check back, what is exactly needed.

Does this satisfy the basic need, or what features do you feel apropriate for this view? 
![image](https://github.com/user-attachments/assets/9439520a-7081-425b-868a-5ee75ae84151)

**Comment by Xyndra** [comment]
Maybe make it a bit transparent
