### ISSUE TITLE
License Problems

### ISSUE THREAD

**Issue by Xyndra** [eythaann/Seelen-UI#218]
The current license makes it impossible to contribute to the project (no modifications allowed), and even create private changes. This is very much against the spirit of open source and additionally not very good for you, the owner, who wants the project to become as good as possible. I can understand putting repositories as non-commercial, not allowing distribution and forcing credit to the original author, but disallowing changes makes impossible for users to add the features they want to the repository without breaking the license. This project can have a great future since the features in it are the reason a lot of Windows users are switching to Linux, however I believe it would be a lot better if the users, who probably are mostly developers, could simply help and add the features/bugfixes they want.

**Comment by Xyndra** [comment]
Personally, I would recommend something like this: https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by eythaann** [comment]
Hi xyndra thanks to try to improve the contribution community!.

Currently users are able to contribute to the project or fork it if is for personal purpose. The license is mainly to avoid redistribution of the app on other than officials distribution platforms, and in reality I don't know much about licenses so the license could change to be dual license.

**Comment by Xyndra** [comment]
> Hi xyndra thanks to try to improve the contribution community!.
> 
> Currently users are able to contribute to the project or fork it if is for personal purpose. The license is mainly to avoid redistribution of the app on other than officials distribution platforms, and in reality I don't know much about licenses so the license could change to be dual license.
> 

Thanks for your quick reply. The issue is that, while forks are allowed by GitHubs TOS, contributions to said forks are not, and the license denies modifications, which those contributions would be. Use is for personal reasons, not redistribution and modification.

**Comment by Xyndra** [comment]
Generally, for licenses there are the following considerations:
 1. modifications or no modifications (currently no modifications)
 2. distribution or no distribution (currently no distribution)
 3. commercial or private only (currently private only)
 4. credit or no credit (currently inapplicable cause no distribution)
 I suggest you go here if you don't know what you are looking for and want a license that people feel safe using (note that the licenses cannot be changed in hindsight though, so choosing something more restrictive later will be impossible):
 https://chooser-beta.creativecommons.org/

**Comment by Xyndra** [comment]
@eythaann

**Comment by eythaann** [comment]
tell me

**Comment by eythaann** [comment]
I read it, just I will no change the license at this moment, contributions are allowed via the Contributions License Agreements.

**Comment by Xyndra** [comment]
Could you please tell me where those Contributions License Agreements can be found? I only see the polyform restrictive license

**Comment by eythaann** [comment]
https://github.com/eythaann/Seelen-UI/blob/master/CONTRIBUTING
https://github.com/eythaann/Seelen-UI/blob/master/CLA.md

**Comment by Xyndra** [comment]
Oh, I didn't see that. Then, I am fine with the current licensing model.
