### ISSUE TITLE
[BUG] Start Menu and Search stopped working on Win11 23H2

### ISSUE THREAD

**Issue by ramiropistoia** [eythaann/Seelen-UI#220]
**Describe the bug**
Installed Seleen from the Microsoft Store, looks great, but at some time of use the Start Menu and Search don't open, I had to close entirely Seleen for these to work again. Also after uninstalling the taskbar is left hidden

**To Reproduce**
1. Install Seelen from MS Store
2. Press the Seleen menu or the Windows key
3. Start menu and Search box don't open
4. Had to exit or uninstall the program for have these working again

**Expected behavior**
The Start Menu and Search will have to work, and after uninstalling the app the Taskbar will restore to visible

**Screenshots**

**Comment by Xyndra** [comment]
works for me, although it is a bit offset from it's usual position as far as I can tell

**Comment by ramiropistoia** [comment]
yes, in Windows 10 the taskbar is centered  like W11 and the Start menu and Search box appears on the left (when it does)

**Comment by eythaann** [comment]
So this is win10 or win11? on win11 never hear more about this, so I'm closing this.
