### ISSUE TITLE
[LANG] Spanish language translation errors

### ISSUE THREAD

**Issue by ramiropistoia** [eythaann/Seelen-UI#221]
**Description of the Error** 🛠️
Various mistranslations on Spanish, like "Cerca" for Close, actually "Cerrar"
Also, many things in English, like the time and date, that should follow the system format (language, 24h or AM/PM, etc)
Acentuar el color - Color de acento (Accent color)
Barra elegante - I don't know how to translate this (fancy toolbar)
La pared (?) - Fondo de pantalla is Wallpaper, and also "La Pared" don't sound attractive to Spanish speakers like "The Wall" in English
Palanca - Probably like "alternar" (Toggle) Palanca is like the toggle as a physical device "interruptor"

**Screenshots** 📸
![Captura de pantalla (787)](https://github.com/user-attachments/assets/4c31d2be-d339-4198-849a-b1a44b17b406)
![Captura de pantalla (788)](https://github.com/user-attachments/assets/ae9cae38-7aac-490f-bfb1-957bf2fe0c86)
![Captura de pantalla (789)](https://github.com/user-attachments/assets/37b82f3f-2e94-4e04-84dc-2be8c09325a6)
![Captura de pantalla (790)](https://github.com/user-attachments/assets/91bb1546-44eb-41d4-89ab-7151fafc55c7)
![Captura de pantalla (791)](https://github.com/user-attachments/assets/bb35d2d7-7db7-4610-9ed6-1dbd17c152e0)
![Captura de pantalla (792)](https://github.com/user-attachments/assets/b5a7b4cb-6001-4349-add6-1930327f82bb)

**Additional Context** ℹ️
I'm using Windows in Spanish language, I'm a native Spanish speaker and these things looks like translated by AI or Google Translate

**Comment by eythaann** [comment]
la pared deberia se "El Muro" jaja si yo tambien hablo esp pero todo lo hago en ingles asi que no reviso las traducciones, si puedes y tienes tiempo PR mejorando las traducciones son bienvenidos :D

**Comment by ramiropistoia** [comment]
> la pared deberia ser "El Muro" jaja si yo tambien hablo esp pero todo lo hago en ingles asi que no reviso las traducciones, si puedes y tienes tiempo PRs mejorando las traducciones son bienvenidos :D

vi que eres de Ecuador, genial aunque generalmente no se usan los artículos "El Muro" no suena muy bien tampoco, quizás sólo Muro

**Comment by PhantomPixel-0418** [comment]
> Barra elegante - I don't know how to translate this (fancy toolbar)

barra de herramientas
![image](https://github.com/user-attachments/assets/d4a0c34d-a784-45cc-a9a5-6391fe9d7f4b)
