### ISSUE TITLE
[FEAT] Autohiding Fancy Toolbar

### ISSUE THREAD

**Issue by Kai7os** [eythaann/Seelen-UI#23]
A feature to autohide the fancy toolbar would be super appreciated!

**Comment by eythaann** [comment]
https://cdn.discordapp.com/attachments/1225056294587858955/1276382051666366555/Recording_2024-08-22_2220531.mp4?ex=66c952eb&is=66c8016b&hm=9b7d394478f1ea42b4d81dca0bfee38b297945448e99f62068b69aa5e23d5496&
