### ISSUE TITLE
[BUG] Certain Program (Figma) resized when minimized

### ISSUE THREAD

**Issue by jinnius0410** [eythaann/Seelen-UI#230]
**Describe the bug**
When using Figma, if I minimized it by clicking the minimized icon (top right) then open it again (by clicking the Figma icon on the taskbar), it bring Figma up normally. But if I minimized Figma by clicking the Figma icon in taskbar, when I click it again to bring Figma up, Figma will be resized to a very small window (instead of being full-screen like it previously was)

**To Reproduce**
1. Open Figma
2. Maximized app window
3. Click Figma icon in Taskbar to minimized
4. Click Figma icon in Taskbar again to bring app window up
5. See error

**Expected behavior**
Able to minimized and bring the app window up normally like every other app

**Screenshots**
![image](https://github.com/user-attachments/assets/97b4d3e1-7a61-457d-86a4-7839b0402fce)

**Comment by lycis** [comment]
The same bug applies with other applications as well (e.g. Microsoft Outlook always comes up in a small window even it was maximized before).

**Comment by Xyndra** [comment]
Potential cause: I am guessing this happens because a position change or resize (because of different work areas) gets called

**Comment by Vehlore** [comment]
Yep, this issue is not particular to one app, it happens with many others.

**Comment by eythaann** [comment]
This should be already fixed, someone can try it?

**Comment by jinnius0410** [comment]
just tried it with Figma, yea I think the issue is fixed! Thank you so much!
