### ISSUE TITLE
[BUG] "Open System Tray" triggers ALLM on LG NANO85 55" 2020 resulting in color profile loss

### ISSUE THREAD

**Issue by SPECIES8472XGN** [eythaann/Seelen-UI#231]
**Describe the bug**
"Open System Tray" triggers ALLM on LG NANO85 55" 2020 resulting in color profile loss. Clicking empty Desktop area, restores color.

**To Reproduce**
1. Select "Open System Tray"
2. Navigate Mouse up and down the running apps in the list.
3. ALLM Banner Appears, display turns black for 1-2 seconds - HDR Color Profile is lost.
4. Select any empty area on the Desktop, ALLM Banner appears, HDR Color Profile is restored.

AMD7900XT
3840x2160 120Hz
Driver: 24.9.1
LG 55NANO85UNA
Windows11 24H2 (26120.2130) (Insider build - Dev branch)

**Expected behavior**
Color Profile loss should not occur when selecting "Open System Tray" or any app in the System Tray.

**Screenshots**

**Comment by Xyndra** [comment]
This probably means there is an application in the system tray that is able to so that. Please test with the normal system tray whilst this applies is off and see what action triggers the loss of profile.

**Comment by SPECIES8472XGN** [comment]
This is my daily driver, normal system tray works without issue. This issue only occurs with Seleen UI.

There's no difference between SDR and HDR, various resolutions, and various bit-depths. Start 11 does not suffer from the issue.

Just an FYI, I'm a Technical Product Manager for display products.

Odd thing about the issue is that I only must click and hover over apps in the system tray for the issue to occur.

Does the app utilize any ALLM metadata?

I will send you a link to a video shortly.


Sent from Samsung Galaxy smartphone.
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Xyndra** [comment]
I meant if you disable SeelenUI and you go onto normal system tray, what do you have to do to change it. Please try hovering, clicking and right-clicking the icon in the normal system tray and report which of those can cause changes, if any.

**Comment by SPECIES8472XGN** [comment]
Hello, Done this already. Disabling SeleenUI results in "zero" issues with the system tray. I can hover, right click, and open apps without an issue.

Link to Video is below. In the meantime, I will continue to troubleshoot. 🙂

https://drive.google.com/file/d/1_OqU8LumyJds7BLrVQJndVNtRndh8D7w/view?usp=sharing

And thanks for the replies. I like SeleenUI quite a bit.
________________________________

**Comment by SPECIES8472XGN** [comment]
More.. 🙂

Leave Seleen UI enabled, disable Fancy Toolbar - no issue with ALLM.

In addition, selecting notifications, clock and other items on Fancy Toolbar results in the issue.

AMD released a new driver, 24.10.1 - no change.

________________________________

**Comment by Xyndra** [comment]
From the video it looks like it falsely recognizes SeelenUI as a game to me for some reason. Perhaps try to look if you can manually mark SeelenUI as a non-game somewhere in your GPU settings

**Comment by eythaann** [comment]
Yeap, literally the issue is cuz your monitor sorfware (I think it is or maybe you graphics software) detects Seelen UI as a game so it is doing some things on your monitor I supose to optimize the refresh rate while gaming or something like that, but this is not a Seelen UI issue, search for a option on your using software to mark the app as not a game.

**Comment by eythaann** [comment]
And responding to: Why only on hover?. Well the app has some "collision boxes" when the mouse is hover the app it activate the app to receive mouse events, other twice the app will be not receiving mouse events, so is on a "disabled" state

**Comment by SPECIES8472XGN** [comment]
Agreed.

TV has limited settings for ALLM - either enabled or disabled. Windows native GPU settings have no affect either. I will see if I can exclude SeleenUI using Registry.

Keep you posted. :-)

Sent from Samsung Galaxy smartphone.
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
