### ISSUE TITLE
[BUG] Windows 11 24H2 Icons reduced after quit/uninstall

### ISSUE THREAD

**Issue by Kraiggers** [eythaann/Seelen-UI#233]
**Describe the bug**
After trying Seelen (very cool, not for me).  I quit and uninstalled it, but my taskbar icons are now much smaller.  I can find no way to restore them to the previous size.

I see no options for taskbar size in the windows settings personalization options.

I tried adding the registry keys TaskbarSi (2) and IconSizePreference (1).  Neither made any difference.

Any advice would be appreciated.

**Comment by eythaann** [comment]
Our app doesn't modify anything on the registry, so this issue doesn't fit with the Seelen UI app.
