### ISSUE TITLE
Please Add Support for Brave Apps

### ISSUE THREAD

**Issue by TheStxfan** [eythaann/Seelen-UI#234]
**Is your feature request related to a problem? Please describe.**
I like this project a lot. Unfortunately there are still a lot of bugs, but it's one of my favorites until now.
When I pin a Brave App to the Dock, if there is already a pinned one, it replaces the old one. If there is not, it correctly adds it, but the new windows manager does not work on that App and the Dock doesn't detect it as opened. I haven't tried with other browsers.

**Describe the solution you'd like**
I would like to request support for Brave Apps in the Dock. 

**Describe alternatives you've considered**
There are no alternative solutions.

**Additional context**
There is no additional context.

**Comment by Xyndra** [comment]
What is a "Brave App"? Do you mean the browser "Brave"? If yes, why would you pin it multiple times?

**Comment by TheStxfan** [comment]
Hello again,

Apologies for the incomplete explanation earlier.

A Web App is technically called a "Progressive Web Application" (PWA), which is a feature most modern browsers support. You can learn more about it in this video: https://www.youtube.com/watch?v=bvTuy2I3GZ8.

Here are some tips that might help:
- In recent Brave versions, the "Create shortcut..." option has been moved from the "More tools" section to the "Save and share" one.
- In the "Save and share" section, you’ll also find "Install 'web_app_name'", which is a shortcut for "Create shortcut..." > "Open as window" (a faster way to install a Web App).
- If the "Open as window" option disappears when using "Create shortcut...", you can re-enable it by visiting "brave://flags/" and disabling the "Shortcuts not Apps" option.

I hope this explanation clears things up!

**Comment by eythaann** [comment]
For now PWA only working fine for edge, I has to test with PWA on chrome i suppose it will fix this too.

**Comment by eythaann** [comment]
PWA working on all Chrome based browser, since v2.0.13
