### ISSUE TITLE
[FEAT] Dock, app hover highlight

### ISSUE THREAD

**Issue by mrdvojo** [eythaann/Seelen-UI#235]
**Is your feature request related to a problem? Please describe.**
It's not a problem per say. But currently, when hovering over an app in the dock, there is no highlight to visually distinguish the item that is currently being hovered over.

**Describe the solution you'd like**
Implement a visual highlight for app that is hovered, preferably with same styled underline as when an app is active (opened).

**Comment by eythaann** [comment]
can you share a video/design example on how do you think the default hover animation should be?

**Comment by mrdvojo** [comment]
Underline bar could have same design as one that is for when App is in active view (as shown in screenshot) and animation could be something like I did some time ago for website (as shown in video) or it also could just be simple fade-in / fade-out that could be even better I think, or just something similiar really.

![Screenshot 2024-10-24 104331](https://github.com/user-attachments/assets/057019ab-9423-4323-998c-f0006699b66f)
https://github.com/user-attachments/assets/f5b86c6f-d4cd-4417-a651-06011b36ecf7

**Comment by eythaann** [comment]
well currently the hover, zooms the icon so to me is enough and you can add custom animations via themes.
![image](https://github.com/user-attachments/assets/3e1d2cea-3e6b-4eda-a235-205aa3b19abe)

**Comment by mrdvojo** [comment]
Was that added in new release because for me nothing changes in hover state, I am using 2.0.4

**Comment by mrdvojo** [comment]
Nope, animations are enabled

**Comment by Xyndra** [comment]
> that is enabled by default, do you have something like disabled animations on your system maybe?

I have anims disabled but it still works for me

**Comment by eythaann** [comment]
well so, idk why the animation doesn't work for u.

**Comment by mrdvojo** [comment]
Fixed it I am just dumb accedentaly set zoomed in size same as normal size in app settings and didn't notice. So this can be closed I think, my bad in the end. :D

**Comment by eythaann** [comment]
hahahaha
