### ISSUE TITLE
[FEAT] Auto-Hide Dock: Improve Trigger Area

### ISSUE THREAD

**Issue by UltraHQ** [eythaann/Seelen-UI#241]
**Description:**
Currently, when "auto-hide dock" is enabled, the dock only reveals itself when the mouse cursor hovers over the exact area it occupies on the screen. This behavior is inconvenient, especially on ultrawide monitors where the dock may occupy a small area.

**Expected behavior:**
The dock should become visible when the cursor reaches the edge of the screen where the dock is located, regardless of the cursor's precise position. This would improve usability by:
- Increasing the target area: Making it easier to trigger the dock's appearance.

**Additional context:**
This issue is particularly noticeable on ultrawide monitors with smaller docks (i.e., fewer apps pinned). The current behavior requires precise cursor movement to reveal the dock, which can be frustrating and inefficient.

**Possible solutions:**
- Expand the invisible "activation area" around the dock's hidden position to make it easier to trigger.

**Comment by Lemagex** [comment]
I came here to recommend the same thing, increasing a trigger area would be good, but additionally I would like to be able to customise the width of that area too. Not just increased to the full edge, but decrease as well.

**Comment by eythaann** [comment]
someone can check how this works on mac? just to be clear on the UX of this behaviour.

**Comment by eythaann** [comment]
@UltraHQ remember that all changes are testable via nightly updates, you can try it and see if all is ok.
