### ISSUE TITLE
Issue with opening minimized apps from the dock

### ISSUE THREAD

**Issue by Joshua-Nweze** [eythaann/Seelen-UI#247]
Sometimes when I try to open a minimized app from the dock, i'll have to click the app icon twice before it opens. After the first click the app's name will be shown in the toolbar, but the app wont open, i'll have to click the app icon again for the app to be opened/displayed on the screen.

**Comment by Vehlore** [comment]
I think this is the same I reported [here ](https://github.com/eythaann/Seelen-UI/issues/179) the other day as well.
