### ISSUE TITLE
[BUG] Exitlag doesn't work with the dock.

### ISSUE THREAD

**Issue by Lemagex** [eythaann/Seelen-UI#248]
**Describe the bug**
Exitlag does not show up on the taskbar when open, similar to steam.

**To Reproduce**
1. Open Exitlag
2. Even when the window is visible, it does not show on the dock.

**Expected behavior**
Interact-able via dock or visible on dock when open.

**Comment by eythaann** [comment]
![image](https://github.com/user-attachments/assets/f7919290-c941-43ca-a619-ebc4e6e1e350)

just have to run the app as administrator to show other admin windows.
