### ISSUE TITLE
[BUG] Crashes after some time.

### ISSUE THREAD

**Issue by DharshanPrakashP** [eythaann/Seelen-UI#261]
**Describe the bug**
while we use your Product, after some time it crashes and makes our computer to stuck and we cant even work on our Normal UI

**To Reproduce**
1. Let your prduct to run in for more than Few Hours, and you will face this issue.

**Expected behavior**
need to be a smooth and stable till we uninstall.

**Comment by eythaann** [comment]
Like this is old, and no log files were provided, there's no way to know what happen at the moment of your app crash. If you replicated it, please send the log files immediately after the crash.
