### ISSUE TITLE
[FEAT] Adjust volume using mouse scroll wheel

### ISSUE THREAD

**Issue by yugo2911** [eythaann/Seelen-UI#263]
**Is your feature request related to a problem? Please describe.**
When laying on bed with laptop on my lap, I mostly use the mouse cuz its not comfortable to keep the left hand on laptop keyboard

**Describe the solution you'd like**
I would like be able to configure the audio using mouse scroll wheel

**Describe alternatives you've considered**
Using keybind, on my laptop its fn+f2/f3, but would prefer mouse way more

I did not notice how often i use the volume adjust until it was gone :o

**Additional context**
Something like windows has
![explorer_ZAgIVmWtvr](https://github.com/user-attachments/assets/a30a3f86-461a-4485-a544-b4ab22a23930)

**Comment by zsmith515** [comment]
I 2nd this.

**Comment by ljbred08** [comment]
Actually, for the best way to change the volume with the mouse, I highly recommend [Volume2](https://github.com/irzyxa/Volume2). It lets you change the volume by moving the mouse on the screen edges (or with the scroll wheel) and is very useful; it would be hard for me to not have it on a computer.
