### ISSUE TITLE
[BUG] Intereference with Lively

### ISSUE THREAD

**Issue by Vehlore** [eythaann/Seelen-UI#264]
**Describe the bug**

While using Lively Wallpaper app, having Seelen makes the wallpaper stay static when the option for pausing on full screen apps is activated in the Lively configuration. Somehow lively detects Seelen as full screen app.

**To Reproduce**

1. Install Seelen and Lively.
2. Apply a live wallpaper.
3. Open the Seelen start menu and close it by clicking on the icon again.
4. Can also reproduce opening any (file manager for example) and closing it on the close button.
5. The wallpaper will pause reproducing until selecting another window or pressing tab, for some reason.

**Expected behavior**

Wallpaper should reproduce continuously unless a full screen app would start.

**Screenshots**

https://github.com/user-attachments/assets/d60ddd4d-8191-4291-9258-3991f2701ba2

**Comment by eythaann** [comment]
like Seelen includes it owns wallpaper engine, there is not objective to made it work with others, btw this is a issue of lively detecting seelen ui as a fullscreen app.
