### ISSUE TITLE
[FEAT] System Tray Icon-only mode

### ISSUE THREAD

**Issue by luisfos** [eythaann/Seelen-UI#277]
**Is your feature request related to a problem? Please describe.**
Opening the system tray with labels can be too large when you have many apps in the tray.
Some of the Icons are also incorrect
![image](https://github.com/user-attachments/assets/278e619c-e39c-43f0-868b-7a6e21fe6b11)

**Describe the solution you'd like**
An option for icon-only system tray like in default windows would be appreciated
![image](https://github.com/user-attachments/assets/155910cc-a9ee-49fb-8aba-94d085d70147)

**Comment by eythaann** [comment]
This can be done via custom themes.
