### ISSUE TITLE
[BUG] All its on fire!.

### ISSUE THREAD

**Issue by Scorpions-09** [eythaann/Seelen-UI#283]
Describe the bug
After installing the application, no notification alerts are received for incoming messages, even when notifications are enabled in the device settings.

To Reproduce

Install the application on a supported device.
Log in to the application and ensure notifications are enabled in both the app settings and the device settings.
Send a message to the account from another device or user.
Observe that no notification alert appears for the incoming message.
Expected behavior
A notification alert should appear on the device when a new message is received, with sound or vibration based on the settings.

**Comment by PhantomPixel-0418** [comment]
Please install the latest version [v2.0.5](https://github.com/eythaann/Seelen-UI/releases/tag/v2.0.5)
This version has a notification preview alert (#215)
![image](https://github.com/user-attachments/assets/90669c4b-b02b-4f4c-b039-5bb5fca1a2e2)
Sounds will be added in future versions!

### Timeline for new features
v2.1.X
- This version will be focused on Notifications, app badges, animations/sounds related to notifications.
- Expose a function to show custom popups/dialogs to users (ex: Confirm shutdown)
