### ISSUE TITLE
[BUG] media module display incorrect when dock is on the left

### ISSUE THREAD

**Issue by DarkLeaves** [eythaann/Seelen-UI#30]
**Describe the bug**
when dock is on the left, the media module  beyound the dock boundary
![图片](https://github.com/user-attachments/assets/c4610979-5e55-49d2-8853-231a2ef78b79)

and when a program window is maximized, the dock bar will automatically hide, but the media module will still display a part of it.
![图片](https://github.com/user-attachments/assets/4c4e5f6b-578d-465d-8d51-93825945f4b6)

**To Reproduce**
1. set the dock to the left of the screen

**Expected behavior**
the media module will change its shape

**Comment by DarkLeaves** [comment]
more than that, after I removed the media module from the dock, dock has only one icon left, the start menu.
(btw, I am using two monitor)
![图片](https://github.com/user-attachments/assets/d9f8d3d6-f92a-48bc-805a-b24033342d91)

**Comment by eythaann** [comment]
![Seelen UI Media Module on left with minecraft background](https://github.com/user-attachments/assets/bad304b1-2a78-448f-9582-390a52489b3f)
