### ISSUE TITLE
There is some software that clicking in the system tray does not show this software. There are also some software that will not appear in the system tray or taskbar when running, such as League of Legends .....

### ISSUE THREAD

**Issue by MoMei1583** [eythaann/Seelen-UI#304]
1. Some software will not show up in the system tray when you click on it. There are also some software that will not appear in the system tray or taskbar when running, such as League of Legends or the software pictured at ......
![image](https://github.com/user-attachments/assets/8d23afd9-e79f-4892-9419-610ebb52760d)
3. The second bug is that I use a bluetooth headset connected to the PC. the Seelen-UI crashes when the bluetooth is disconnected, or when it's connected (I think it's because of a problem with the bluetooth in the toolbar or the sound there).
![Snipaste_2024-12-03_13-52-19](https://github.com/user-attachments/assets/d22c0030-6570-4e20-b798-e1696a98273c)

**Comment by MoMei1583** [comment]
LoL's application interface, for example, doesn't show up in the taskbar.
![Uploading image.png…]()

**Comment by MoMei1583** [comment]
![image](https://github.com/user-attachments/assets/999eda30-06be-4149-aa81-50616e01d814)

**Comment by eythaann** [comment]
Strange, I play LOL, and it is shown as normal, could be an issue with the language, (is common having issues with UTF16 languages)

**Comment by eythaann** [comment]
about the xbox game bar could you right click on it and go to file location, and share me the name of the executable.

**Comment by MoMei1583** [comment]
> Strange, I play LOL, and it is shown as normal, could be an issue with the language, (is common having issues with UTF16 languages)奇怪，我玩LOL，显示正常，可能是语言问题（UTF16 语言常见问题）

Maybe, Then I don't care about question. The other issue is bluetooth headset, UI will be turned off when it open and closes

**Comment by MoMei1583** [comment]
> about the xbox game bar could you right click on it and go to file location, and share me the name of the executable.关于 xbox 游戏栏，您可以右键单击它并转到文件位置，然后告诉我可执行文件的名称吗？

I'll do as you say. Thanks.

**Comment by eythaann** [comment]
> Maybe, Then I don't care about question. The other issue is bluetooth headset, UI will be turned off when it open and closes
yeah probably it is for the language too.

**Comment by MoMei1583** [comment]
> > Maybe, Then I don't care about question. The other issue is bluetooth headset, UI will be turned off when it open and closes
> 
> yeah probably it is for the language too.
Ok!

**Comment by luriusTM** [comment]
> > > Maybe, Then I don't care about question. The other issue is bluetooth headset, UI will be turned off when it open and closes
> > 
> > 
> > yeah probably it is for the language too.
> > Ok!

I'll see on that, what heppens, am I able to reproduce. Also, the missing app is a mystery which can be discovered, Genshin does not has visible app also... so it is intresting and I can reproduce for sure. 
![image](https://github.com/user-attachments/assets/c3d2ba5f-83d5-41e2-8c39-5dfbd2125af0)

**Comment by eythaann** [comment]
@MoMei1583 just run Seelen-UI as admin, it will fix the issue of the app.

**Comment by luriusTM** [comment]
We dig a bit in this case, our best guess from my instance that, the game you running is using elevated rights. Seelen not runs as admin by purpose, but because of this, Seelen can not see and manipulate these applications. 

I tried out bluetooth case also, it seems for me it connects and functional as it should... so my best guess that, eythaann had right and it will be an encoding somewhere.

**Comment by eythaann** [comment]
On this issue ticket only the xbox app was removed from dock, create separated issues, not a bunch of them the next time please.
