### ISSUE TITLE
[BUG] Failed to open the system tray.

### ISSUE THREAD

**Issue by likely-cloud** [eythaann/Seelen-UI#307]
The screen flickers after clicking on the system tray in the system bar, and then the system tray only displays a black rectangle.
![picture](https://github.com/user-attachments/assets/137457da-1020-46b9-b905-a314edcfaf87)

**Comment by likely-cloud** [comment]
Windows Version Information
![image](https://github.com/user-attachments/assets/b7ed8431-a72c-4ffa-9f66-77537f7420e4)

**Comment by Joshua-Nweze** [comment]
i have also experienced this

**Comment by likely-cloud** [comment]
I solved this issue by turning on the hidden icon menu switch in the system tray.
![打开系统托盘的隐藏图标菜单](https://github.com/user-attachments/assets/a8f09b78-d568-4c69-bb3f-18757df49f87)
