### ISSUE TITLE
[BUG] System Tray is blank

### ISSUE THREAD

**Issue by DarkLeaves** [eythaann/Seelen-UI#31]
**Describe the bug**
when I click System Tray button, it just display a small narrow blank.

**To Reproduce**
1. run seelen ui
2. click System Tray button

**Screenshots**
![图片](https://github.com/user-attachments/assets/69c85e7f-1953-409d-b50e-2e33c537ebf8)

**Comment by Adsicmes** [comment]
i also have this bug
