### ISSUE TITLE
[BUG] APP message notification failed

### ISSUE THREAD

**Issue by RuoCJ** [eythaann/Seelen-UI#311]
**Describe the bug**
There is a problem, when using seellen, the wechat in the lower right corner will not blink after receiving a message, is there a problem with my configuration?

**To Reproduce**
1. Use Seelen
2. Log in to wechat (maybe other apps that accept messages can also work)
3. Send a message to the account that is logged in to the computer

**Expected behavior**
There should be a corresponding message prompt

**Screenshots**
The normal situation is as follows:
![PixPin_2024-12-05_11-12-34](https://github.com/user-attachments/assets/26cc2bae-e6cd-4d7f-95e9-f5cdc810eafb)

After using Seelen:
![image](https://github.com/user-attachments/assets/6b1b3c6c-834a-4c72-95ba-0511f6f5af2a)

**Win Version : Win11 23H2**

**Comment by eythaann** [comment]
Will be fixed on #282
