### ISSUE TITLE
[BUG] System tray automatically hides

### ISSUE THREAD

**Issue by RuoCJ** [eythaann/Seelen-UI#312]
**Describe the bug**
When I open the system tray through the three dots in the upper right corner, then I right-click on one of the programs listed in the system tray, and the system tray automatically disappears

**To Reproduce**
1. Open the system tray at the three points in the upper right corner of the single machine
2. Right-click an APP in the list
3. The system tray disappears

**Expected behavior**
The system tray doesn't disappear when I right-click on an application

**Screenshots**
The specific process is as follows
![PixPin_2024-12-05_11-18-19](https://github.com/user-attachments/assets/6a2de063-b588-460e-b1ff-0d0e10cb03f4)

**Win Version : Win11 23H2**

**Comment by eythaann** [comment]
intended.
