### ISSUE TITLE
[BUG] All its on fire!.

### ISSUE THREAD

**Issue by chrisokoriedev** [eythaann/Seelen-UI#318]
when i off my pc and on the theme is gone some of my setting are gone too and the tab bar has limit on item it will alone 
hmmmmm i really love the theme and yes the function dont work when using is am using a modded windows version not sure if that the reason

**Comment by PhantomPixel-0418** [comment]
You may not have clicked the save button

**Comment by chrisokoriedev** [comment]
i did am guessing it because am using a stripped down modded windows version,

**Comment by eythaann** [comment]
I'm not understanding what is your real issue

**Comment by Eyion** [comment]
By the way, has anyone compared Seelen-UI with Stardock Fences and iTop Easy Desktop?

**Comment by chrisokoriedev** [comment]
> > By the way, has anyone compared Seelen-UI with Stardock Fences and iTop Easy Desktop?
> 
> Is the first time I hear about it, and this threat is for this issue, please create a [discussion](https://github.com/eythaann/Seelen-UI/discussions) to make questions the next time.

okay noted
