### ISSUE TITLE
The taskbar and other displays are automatically hidden

### ISSUE THREAD

**Issue by SONGjiemo** [eythaann/Seelen-UI#319]
![image](https://github.com/user-attachments/assets/7231a5f1-b71e-4637-b12a-f8cc1401e3fd)
The position of the arrow returns to the desktop, automatically hiding the taskbar and other displays ...

箭头指向的位置会回到桌面自动隐藏任务栏等显示。
设置不会自动隐藏任务栏等信息

![image](https://github.com/user-attachments/assets/b66ac874-a11b-4760-b322-4b00bc8762dc)
I set it not to auto-hide. The taskbar and other displays are still automatically hidden
我设置了不自动隐藏。依旧会自动隐藏任务栏等显示

![image](https://github.com/user-attachments/assets/85fa766f-0fc9-47a4-b8c0-76399733bb43)
It often leads to inexplicable return to the desktop. I don't know what to do all of a sudden.
经常会莫名其妙的导致回到桌面上面都没有了。一下子不知道咋办了。

**Comment by luriusTM** [comment]
Give us logs, please, I'm almost sure, there had to be a filesystem / monitor change (or kind of) all of a sudden, and Seelen recognises reload is needed. Other way this should not occour, but log can tell us what happens exactly. 

`C:\Users\{your user}\AppData\Local\com.seelen.seelen-ui\logs`

**Comment by SONGjiemo** [comment]
> Give us logs, please, I'm almost sure, there had to be a filesystem / monitor change (or kind of) all of a sudden, and Seelen recognises reload is needed. Other way this should not occour, but log can tell us what happens exactly.
> 
> `C:\Users\{your user}\AppData\Local\com.seelen.seelen-ui\logs`

Hello, I installed the Microsoft Store version and didn't find the logs in the directory you said.

**Comment by SONGjiemo** [comment]
> Hmm, some user already reported this on discord, Q: the issue is fixed after restart the app? Q2: is the dock hidden like autohide, or like it wasn't created?

After repeated testing, we know the problem.
1. After the software is enabled, the taskbar of the win11 system will be set to: automatically hide the taskbar.
![image](https://github.com/user-attachments/assets/1effcc9d-8d54-4312-bd71-a80fb471291f)

3. After restarting the system, the software will be invalid. But the auto-hide taskbar still works.
4. After enabling the software, the software icon of the taskbar does not have the function of flashing information, which is more important. Because we have customer information at work, we can't get timely information notifications. You have to keep the software client open to see the information.

**Comment by eythaann** [comment]
What?, what exactly we are talking about? native taskbar or seelen dock?

**Comment by SONGjiemo** [comment]
> What?, what exactly we are talking about? native taskbar or seelen dock?

Using your software will cause the taskbar of the win system to turn on automatically ...
![image](https://github.com/user-attachments/assets/2184d5b9-c91b-4a44-837e-8a6c5756f77b)

**Comment by eythaann** [comment]
Expected behavior when dock is enabled.

**Comment by SONGjiemo** [comment]
> Expected behavior when dock is enabled.

I mean, is it possible not to turn on this feature automatically. I want this taskbar to be visible all the time and not hidden
