### ISSUE TITLE
Exclude processes from dock

### ISSUE THREAD

**Issue by strandzen** [eythaann/Seelen-UI#320]
**Is your feature request related to a problem? Please describe.**
Some processes like examples spotify.widget and xbox game bar widgets show up in the dock. 

**Describe the solution you'd like**
I would like to have blacklist for processes to be excluded from the dock

![seelen-ui_hmn6fzVPsL](https://github.com/user-attachments/assets/9e7d8d99-fe8f-4ea4-96ed-b1fa16ebae00)
![seelen-ui_mD5h8r4xCd](https://github.com/user-attachments/assets/aabcf0a8-4351-4ac0-bb0c-dd488780d363)

**Comment by eythaann** [comment]
You can make that, use settings for apps feature.

**Comment by strandzen** [comment]
Okay, thanks! Maybe should be a simplified tab in the Dock/Taskbar settings to be more accessible?
