### ISSUE TITLE
[BUG] after installation taskbar disappears and noting happens.

### ISSUE THREAD

**Issue by Nyxendoescode** [eythaann/Seelen-UI#33]
**Describe the bug**
after running the app my taskbar disappeared nad nothing happens.

**To Reproduce**
1. download the exe file
2. install the exe file 
3. run the app

**Expected behavior**
idk

**Screenshots**
![Screenshot 2024-08-21 194745](https://github.com/user-attachments/assets/638105bb-2504-45da-91d9-29540bfc74dc)

**Comment by eythaann** [comment]
please send me the file at: `C:\Users\{your user}\AppData\Local\com.seelen.seelen-ui\logs` to see what is happening.

**Comment by Nyxendoescode** [comment]
[Seelen UI.log](https://github.com/user-attachments/files/16693109/Seelen.UI.log)
here it is

> please send me the file at: `C:\Users\{your user}\AppData\Local\com.seelen.seelen-ui\logs` to see what is happening.

**Comment by Nyxendoescode** [comment]
fixed it after reinstalling webview2 runtime
