### ISSUE TITLE
[BUG] Volume and sound options not showing

### ISSUE THREAD

**Issue by Joshua-Nweze** [eythaann/Seelen-UI#330]
I tried to restart Seelen and the volume icon is showing as mute, when I click it to open the volume options, nothing was showing.
After a while Seelen crashes

![Screenshot 2024-12-09 132926](https://github.com/user-attachments/assets/e5b3a433-6dcd-4f9a-925b-3987339b261f)

**Comment by eythaann** [comment]
Send me the log file, please.

**Comment by Joshua-Nweze** [comment]
i restarted seelen couple of times and it's now working,
should i send it anyway??

**Comment by eythaann** [comment]
nice, If this happens again, send it immediately, like logs are deleted after some time of use.

**Comment by Joshua-Nweze** [comment]
ok
