### ISSUE TITLE
[BUG] PowerToys Run won't open when toolbar is focused

### ISSUE THREAD

**Issue by hexadecimal233** [eythaann/Seelen-UI#34]
**Describe the bug**
When focusing the toolbar, pressing `Alt + Space` wont open the PowerToys Run window.

**To Reproduce**
1. Focus the toolbar
2. Open the PowerToys Run

**Expected behavior**
PowerToys Run normally opens

**Screenshots**

**Comment by hexadecimal233** [comment]
I can confirm Seelen UI is not elevated. 
![image](https://github.com/user-attachments/assets/950870f4-283c-4ff4-ba4c-b02515235b24)
and I when I disable `Disable hotkeys when fullscreen`, PowerToys Run works.

**Comment by eythaann** [comment]
> I can confirm Seelen UI is not elevated. ![image](https://private-user-images.githubusercontent.com/62250232/359945729-950870f4-283c-4ff4-ba4c-b02515235b24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTA1NTcsIm5iZiI6MTcyNDI1MDI1NywicGF0aCI6Ii82MjI1MDIzMi8zNTk5NDU3MjktOTUwODcwZjQtMjgzYy00ZmY0LWJhNGMtYjAyNTE1MjM1YjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE0MjQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNTI1ZmE4YTNlNTg3NTVhZmU0ZDM2ZTBjMDE5MWQyOTVkMDFlZDAxZGMzMzg0M2QxMjdhNWViY2FjMTYxNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Smi7fqHJyzxos4NyMjGDs8dmZwjZi10ehOBjA8OmzvE) and I when I disable `Disable hotkeys when fullscreen`, PowerToys Run works.

oh, so that is, powertoys use the same way that I use in seelen to check if a app is fullscreen and it is check the size of the window compared to the monitor, btw this will still marked as not planned.
