### ISSUE TITLE
Add Special Function button pop-ups and/or improve them.

### ISSUE THREAD

**Issue by kashifayan** [eythaann/Seelen-UI#349]
Modern Laptops and Most Modern Keyboard have special keys called "Function Keys (Fn)" that allow you to perform a specific function, among them, some of them being the ability to adjust the Brightness and the Volume of the device. 
While Seelen-UI does include a volume slider that appears when you use the Volume keys (Up or Down). This does not appear when an app is in Fullscreen Mode (for example when watching a video in Fullscreen)- Whereas Windows's stock Volume slider does- this can be even more important in games, where you usually don't want to exit Fullscreen,
And there is no Brightness Slider for The Brightness Keys (up or down).it would be nice to have one for them of course have them even during Fullscreen Mode
While we are at it, why not add a number indicating the value they are at( For both Brightness and Volume functions)?
although that is less important but still nice to have.

**Comment by eythaann** [comment]
you can create custom items for toolbar, and add the volumen level on it.

**Comment by eythaann** [comment]
About the brightness, there's other issue for it, so I'm closing this one.
