### ISSUE TITLE
[BUG] `Windows Settings` / random programs  does not show on the dock.

### ISSUE THREAD

**Issue by hexadecimal233** [eythaann/Seelen-UI#35]
**Describe the bug**
`Windows Settings` does not show on the dock. Sometimes it shows up as a ghost window and cannot be closed.

**To Reproduce**
1. Open a window
2. ...

**Expected behavior**
The windows should disappear / appear on the dock.

**Screenshots**
![image](https://github.com/user-attachments/assets/2cd94b81-648b-4b3f-a200-c7ce14417b4c)
This is the PowerToys Settings window and it still shows on the dock even it was closed. Clicking/Closing on it does nothing.

**Comment by Tsubajashi** [comment]
to add to it, ive seen similar behaviour that it randomly shows the Xbox Game Bar, even though it was never opened actively by me, and also happened when i didnt turn on any game. im not sure what triggers that behaviour, as i took a nap while it happened.

**Comment by eythaann** [comment]
> to add to it, ive seen similar behaviour that it randomly shows the Xbox Game Bar, even though it was never opened actively by me, and also happened when i didnt turn on any game. im not sure what triggers that behaviour, as i took a nap while it happened.

@Tsubajashi see #5

**Comment by eythaann** [comment]
I thought this was already fixed on v1.10 so I will close it but you can reopen it if found something like this again.
