### ISSUE TITLE
[FEAT] Add windows split screen preview in dock

### ISSUE THREAD

**Issue by Joshua-Nweze** [eythaann/Seelen-UI#354]
In windows 11, when the screen is split, to fit 2 or more apps on the screen, the preview of the screens split will be seen in the task bar when one of the screens being split is hovered on.

See example
![Screenshot 2024-12-13 145251](https://github.com/user-attachments/assets/eb3affdb-6f8b-40bf-be95-90a86c103496)

But it's not so in Seelen
![Screenshot 2024-12-13 145637](https://github.com/user-attachments/assets/f4f39c5f-5953-4927-ad61-21a07514b54b)

When the window with the screen being split is clicked on, all the apps that was split with the screen selected will be opened.

When the window with only the app is clicked on, only the app will be opened.

**Comment by eythaann** [comment]
I don't have plans to implement this, maybe a group feature could do a similar behavior, but not via native windows layouts.
