### ISSUE TITLE
[BUG/Feature] Taskbar Icons does not update & Events does not fire

### ISSUE THREAD

**Issue by hexadecimal233** [eythaann/Seelen-UI#36]
**Describe the bug**
The taskbar icons does not update and tooptip doesn't either.
Taskbar events eg. right click, hover is not implemented.

**To Reproduce**
1.Right click icons / hover on the icons.

**Expected behavior**
All events are processed.

**Screenshots**
![image](https://github.com/user-attachments/assets/641dee81-c518-41ea-98b9-a7948593d05a)

**UPDATE**: Some icon require double click to open (eg. SystemInformer), so they cannot open directly from the tray icons.

**Comment by eythaann** [comment]
https://github.com/user-attachments/assets/d9e4b182-4ca4-4d9a-b2c9-1d2318ba9ce5

**Comment by eythaann** [comment]
The double click event can no be done, because it is a self implementation of the tool and no a documented way to handle tray icons, only click and context (and others but no double click) are available officially.
