### ISSUE TITLE
[FEAT] Adding possibility to terminate task in right click menu

### ISSUE THREAD

**Issue by mrdvojo** [eythaann/Seelen-UI#360]
It is possible to enable the "End Task" option (which will force terminate a non-responding app, for example) by right-clicking on the open app in the taskbar. This method is faster than going all the way to the Task Manager searching for proccess and terminating it that way.

It would be nice to have the option to enable or disable the right-click "End Task" option for dock, in the dock settings as well (it is just another item in the list like run as administrator etc).

**Comment by eythaann** [comment]
![image](https://github.com/user-attachments/assets/941d1f11-4625-48ba-9004-5081e81f06ee)
![image](https://github.com/user-attachments/assets/72d46415-5fd9-4312-b089-fdcd42b65427)
