### ISSUE TITLE
[BUG] The MS Store version doesn't work

### ISSUE THREAD

**Issue by ThePixelDude111** [eythaann/Seelen-UI#361]
After updating the app, whenever I launch it, it gives me an error message. I tried repairing the app, resetting it and even reinstalling it, but to no avail.

1. Install the app from MS store
2. Launch the app
3. See error

Here is a screenshot for the error:
![image](https://github.com/user-attachments/assets/3b555f4c-cb6a-4136-bc71-ae6c3995cee0)

**Comment by ThePixelDude111** [comment]
This is on the latest version of the app, on windows 10 22h2 (latest update installed)

**Comment by eythaann** [comment]
fixed on v2.0.12, but store take ages on be updated.
