### ISSUE TITLE
[FEAT] Include Win + Number Hotkey

### ISSUE THREAD

**Issue by BarryTheShen** [eythaann/Seelen-UI#363]
**Is your feature request related to a problem? Please describe.**
On native Windows, it is possible to open the windows on the taskbar using Win + Number. For example, the first application is chrome. I can press Win + 1 to hotkey open chrome. This is super convenient and I wish Seelen can implement this.

**Describe the solution you'd like**

Adding the Win + Number hotkey to open the designated applications on the taskbar/dock
**Describe alternatives you've considered**

**Additional context**

**Comment by PhantomPixel-0418** [comment]
https://github.com/eythaann/Seelen-UI/issues/281
