### ISSUE TITLE
[BUG] The boot-up function often fails.

### ISSUE THREAD

**Issue by Mclarenlife** [eythaann/Seelen-UI#367]
**Describe the bug**
Prior to version 2.0.12 it could boot itself up for the first few days of use. Reinstalling it can fix the problem. But in version 2.0.12 it never booted itself up!

**To Reproduce**
1. Run the software as administrator
2. Turn on the boot-up feature
3. Restart computer

**Expected behavior**
It boots up smoothly and doesn't break after a few days of use.

**Version information**
Seelen UI: v2.0.12+20241214094407
Windows11: 24H2 26100.2454
Language: Chinese

**Comment by PhantomPixel-0418** [comment]
https://github.com/eythaann/Seelen-UI/issues/208

**Comment by jjuny1** [comment]
Same here. 
I really did saved the configuration(auto startup), but every time I boot up my Windows 11 again(Restart/Shutdown and bootup), UI doesn't show up.

**Comment by jjuny1** [comment]
@eythaann I've just installed Github version. (latest)

**Comment by Mclarenlife** [comment]
@eythaann Prior to version 2.0.12, it would leave process in Task Manager when it failed to start. I had to terminate the process to start it again. But in version 2.0.12, it doesn't leave a process when it fails to start. It's as if it never tried to start. I hope this message is useful to you.

**Comment by eythaann** [comment]
It was a bug, fixed on 2.0.11, On crash the process should be closed, now is working correctly.

**Comment by eythaann** [comment]
Also on 2.0.11, a service was added, on crash the app should be restarted automatically by this service, it is called slu-service. This should retry the startup if fails. but looks like is not working as you mention.

**Comment by eythaann** [comment]
@Mclarenlife try latest nightly please, it should be fixed now.

**Comment by Mclarenlife** [comment]
@eythaann I tried. It's been fixed. Thank you!
