### ISSUE TITLE
[BUG] Dock Issues

### ISSUE THREAD

**Issue by hexadecimal233** [eythaann/Seelen-UI#37]
**Describe the bug**
- [x] When you drag window to the left side, it might duplicate into 2 icons (or more)
- [ ] When you try to click some window, it will not be brought to front, or need to click twice to bring them to front.
- [x] Unhovering an icon sometimes the window preview will not disappear.

**Screenshots**
1.
![image](https://github.com/user-attachments/assets/c4e670da-92c0-4ac8-b026-0145ef12ceef)
2. No Image
3.
![image](https://github.com/user-attachments/assets/2c5bc8d1-32ed-406a-8e7e-798b94585af5)

**Comment by eythaann** [comment]
@hexadecimal233 could you make a video replicating the first point?

**Comment by hexadecimal233** [comment]
> @hexadecimal233 could you make a video replicating the first point?

i cannot repro for 100%, cuz this happens randomly (also applies to point 3)

**Comment by eythaann** [comment]
I do a commit that maybe fix the first point, the thirty point it is not relevant the popups are closed if you made a click in any part, so I will close this issue as won't fixed. If you find a way to replicate this issue reopen it.
