### ISSUE TITLE
[BUG] Seelen UI stops working after monitors turn off or computer sleeps

### ISSUE THREAD

**Issue by IriGitt** [eythaann/Seelen-UI#373]
**Describe the bug**
After my displays have gone to sleep (I use an OLED so this is mandatory for me, The UI is no longer visible. Process is still running in task manager no crash or error code displayed)

**To Reproduce**
1. Let the Monitors turn off
2. Wake up computer
3. Default task bar, Dock and FancyToolbar are all invisable. Only way to restore functionality is to kill Seelen ui and re-launch

Further Info
I am using the github version 2.0,12
Windows 11 24H2
Running 2x 1440p monitors, One Landscape and on Portrait

**Expected behavior**
Ui should still be functional upon waking up the PC

**Screenshots**
Nothing to screenshot as nothing is visible, Log attached
[Seelen UI.log](https://github.com/user-attachments/files/18197338/Seelen.UI.log)

**Comment by eythaann** [comment]
potencially fix: 15f246ff80ae433214205de370fe032e138147bd

**Comment by eythaann** [comment]
if this persist after v2.0.13 reopen this issue.

**Comment by callephi** [comment]
Still persisting, version 2.3.8. Windows 11 24H2.
