### ISSUE TITLE
[BUG] Icons not loaded in the Dock

### ISSUE THREAD

**Issue by Mclarenlife** [eythaann/Seelen-UI#391]
**Describe the bug**
I tried installing the latest version after uploading bug number #390. I found a lot of problems with the latest version. One of the most serious problems is that the icons don't load. On top of that there are performance issues, I feel a noticeable lagging.

**Software version**
v2.0.12+2024122010426

**Screenshots**
![屏幕截图 2024-12-23 190448](https://github.com/user-attachments/assets/3c972890-f8ee-4be3-8cdd-3e0562882ccf)

**Comment by eythaann** [comment]
fixed on: e982b06a5ca1e135032f6e32422ddac12e4c0f5e
