### ISSUE TITLE
[BUG] Open failed 

### ISSUE THREAD

**Issue by Adsicmes** [eythaann/Seelen-UI#41]
maybe the next release could fix it?
this utf-8 option may cause other problem on other apps

`[2024-08-22][02:41:36][seelen_ui][ERROR] A panic occurred:
Cause: �[36mFailed to refresh UWP manager: Utf8(FromUtf8Error...`

1.9.10, exe from github release

**Solution**
`Control Panel > Region > Administrative > Language for non-Unicode program`

open `Option Beta: Use Unicode UTF-8 for worldwide language support need to be unchecked before you click OK to exit the window.`

<details>
<summary>log</summary>

[2024-08-22][02:41:36][seelen_ui::seelen_weg::icon_extractor][TRACE] Extracting icon for "seelen-ui.exe"
[2024-08-22][02:41:36][seelen_ui][ERROR] A panic occurred:
  Cause: [36mFailed to refresh UWP manager: Utf8(FromUtf8Error { bytes: [91, 123, 55, 52, 119, 98, 113, 114, 121, 52, 99, 99, 34, 44, 34, 73, 110, 115, 116, 97, 108, 108, 76, 111, 99, 97, 116, 105, 111, 110, 34, 58, 34, 67, 58, 92, 92, 80, 114, 111, 103, 114, 97, 109, 32, 

... (the log is too long so it cant be fully represented)

, 115, 92, 92, 77, 101, 100, 84, 105, 108, 101, 46, 112, 110, 103, 34, 44, 34, 83, 113, 117, 97, 114, 101, 52, 52, 120, 52, 52, 76, 111, 103, 111, 34, 58, 34, 73, 109, 97, 103, 101, 115, 92, 92, 65, 112, 112, 76, 105, 115, 116, 46, 112, 110, 103, 34, 125, 93, 125, 93, 13, 10, 10], error: Utf8Error { valid_up_to: 32773, error_len: Some(1) } })[39m
  Location: [35msrc/background\modules\uwp\mod.rs:19:27[39m
[2024-08-22][02:41:36][seelen_ui][ERROR] A panic occurred:
  Cause: [36mpanic in a function that cannot unwind[39m
  Location: [35mlibrary\core\src\panicking.rs:221:5[39m

</details>

**Comment by eythaann** [comment]
Q: what language do you use in your system?

**Comment by Adsicmes** [comment]
zh-cn

**Comment by eythaann** [comment]
I see, this maybe is a UTF-16 issue on your system, I thought I can search a workaround but I will need your help testing experimental versions. let me do a fast build.

**Comment by eythaann** [comment]
@Adsicmes I can't share a big file here, can you write me at discord?

**Comment by Adsicmes** [comment]
yeah
