### ISSUE TITLE
[BUG] Launching taskbar applications do not work

### ISSUE THREAD

**Issue by TBG09** [eythaann/Seelen-UI#415]
**Describe the bug**
Launching apps from the taskbar will not work, they only launch through run as administrator.
This happens even with no modified settings. (The video says otherwise, but this statement is true)

**To Reproduce**
1. Go to the taskbar
2. Click on any application
4. See what happens.

**Expected behavior**
It was expected to open the application normally without extra steps

**Video**
https://github.com/user-attachments/assets/9df01d6d-959f-428a-bd11-6ec27f97e9b2

**Comment by eythaann** [comment]
already fixed on nightly
