### ISSUE TITLE
[BUG] Start panel not centered

### ISSUE THREAD

**Issue by shakey1** [eythaann/Seelen-UI#42]
**Describe the bug**
When the Start Button (and menu) in Windows 11 are left aligned, clicking the Start Button in Seelen-UI (which is center aligned) the panel still opens on the left.

**To Reproduce**
1. Right click on taskbar (Windows 11) and choose "Taskbar Settings"
2. Scroll down and click on "Taskbar behavior"
3. In the area titled "Taskbar alignment" choose "Left"
4. Start Seelen-UI and click the Start Button.

**Expected behavior**
With the Start Button being center aligned in Seelen-UI, I would expect the start panel to also change to center alignment.

**Screenshots**
![alignment](https://github.com/user-attachments/assets/dc196a8b-913f-4da3-9973-c5f5d433a4c6)

**Comment by eythaann** [comment]
You have to manually change the options in other apps for your customizations. Seelen UI avoids modifies system settings and files.
