### ISSUE TITLE
All in one Problems

### ISSUE THREAD

**Issue by KiraiEEE** [eythaann/Seelen-UI#43]
Hi, I just used the app for about a day, and here are some initial impressions:

Positive Impression:

- This app is a game changer! It completely stopped me from considering a switch to Linux, and I’m even thinking about learning how to contribute to it if possible.

Issues and Concerns:

- Pressing Win + D hides everything, including the Seelin UI.
- The taskbar shows the last app even after it's closed.
- Some apps in the dock are buggy.
- Thumbnails in the dock are stuck loading.
- The volume and brightness bars don’t appear.
- The Wi-Fi in the taskbar doesn’t work.
- The settings window isn’t resizable.
- Managing the window manager is challenging for me and doesn’t seem compatible with the existing Windows settings.

Thanks for the cool app and all the work you’ve put into it—I really love it!

**Comment by eythaann** [comment]
@KiraiEEE I'm trying hide with win + d but nothings happen.

**Comment by KiraiEEE** [comment]
> @KiraiEEE I'm trying hide with win + d but nothing happen.

when i Win+D it shows only the wallpaper and hides the taskbar and dock like its an app too instead of being forced to stay

**Comment by KiraiEEE** [comment]
> @KiraiEEE I'm trying hide with win + d but nothing happen.

When I press Win+D, it shows the wallpaper and hides the taskbar and dock, as if they are a normal app instead of being forced to stay visible

**Comment by KiraiEEE** [comment]
After the update, Seelin doesn't run on Windows startup :')))

**Comment by KiraiEEE** [comment]
- No notification pop-ups.
- No brightness scroll.
- System brightness and volume bars don't show.

**Comment by KiraiEEE** [comment]
okay

**Comment by eythaann** [comment]
all these bugs are done or reported on other tickets, so I will close this.

**Comment by TejBachhav** [comment]
does this cause any issues with the battery usage?
