### ISSUE TITLE
[FEAT]The system tray supports right-click？

### ISSUE THREAD

**Issue by Xiximei36** [eythaann/Seelen-UI#47]
Can the icons in the system tray support right-click context menu options, similar to those in the system tray of Windows 11?

This way, we can quickly manage these applications.

![PixPin_2024-08-23_18-33-22](https://github.com/user-attachments/assets/3be77aec-ee32-4c90-bc74-40eeef2733d9)

**Comment by eythaann** [comment]
ehmm, to me right click is working fine.

**Comment by Xiximei36** [comment]
> Recording.2024-08-23.054946.mp4

Thank you for your reply. I have tried shutting down or running as administrator, but it still doesn't work. I don't know where the problem lies. My system is Windows 11 Enterprise Edition 23H2.

**Comment by eythaann** [comment]
@Xiximei36 can do you share the logs of search for error messages when doing right click?

**Comment by Xiximei36** [comment]
> @Xiximei36 can do you share the logs of search for error messages when doing right click?

Thank you, I'm all good now because I updated the app in the Microsoft Store.
