### ISSUE TITLE
Filter out hidden apps from SeelenWeg

### ISSUE THREAD

**Issue by ashwinjadhav818** [eythaann/Seelen-UI#5]
Some apps which are supposed to be hidden from the dock like yasb, still are visible in the dock whereas they are not visible in the taskbar.
![image](https://github.com/eythaann/Seelen-UI/assets/81229115/e7e0bdeb-5f40-4b13-959f-de788d3b9b16)

**Comment by mystery4f** [comment]
hi,How did you achieve the effect at the top of this picture?

**Comment by eythaann** [comment]
![Seelen UI Hidding a app from dock/taskbar](https://github.com/user-attachments/assets/d004b1d0-720d-422d-97af-ed18a829a8ad)
In this example I'm hidding notepad from the dock.

**Comment by IMB11** [comment]
Game bar doesn't show up in the list `XboxGameBarWidgets.exe`

![seelen-ui_hz47mNITfT](https://github.com/user-attachments/assets/3ff7bafe-bd5a-410b-b6df-8dbdfd2766b6)

**Comment by eythaann** [comment]
> Game bar doesn't show up in the list `XboxGameBarWidgets.exe`
> 
> ![seelen-ui_hz47mNITfT](https://private-user-images.githubusercontent.com/93472213/373567183-3ff7bafe-bd5a-410b-b6df-8dbdfd2766b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMzEzOTgsIm5iZiI6MTcyODAzMTA5OCwicGF0aCI6Ii85MzQ3MjIxMy8zNzM1NjcxODMtM2ZmN2JhZmUtYmQ1YS00MTBiLWI2ZGYtOGRiZGZkMjc2NmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDA4MzgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MGNmNjI3ZDMwZGJlZmE5OTFmNmU1YzNkNjUyYTY5MmRmNzBjNzk4NGIyODMzMmU0ZWU3YjhiMTNiZmJkMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mCIjXnwWoD4YTseH_gtTW8DK_pVJOVkaOCdthjwVIn8)

you can add your own configurations, add a new entry with the app that you want to modify

**Comment by IMB11** [comment]
I tried that but it still doesnt hide
