### ISSUE TITLE
[BUG] Toolbar sometime still shows up on top of fullscreen app

### ISSUE THREAD

**Issue by Dadangdut33** [eythaann/Seelen-UI#50]
**Describe the bug**
It does not always happen, but the toolbar will sometime still shows up on top of app even though the app is in fullscreen. This bug usually happens when you go out of fullscreen and then go back to fullscreen (or do the Win+d shortcut and get back to the app). I tried it with some apps that you can see in the screenshot below (hope it helps).   

**To Reproduce**
1. Go to fullscreen on an app (example: mpv video player)
2. Go out of fullscreen
3. Go back to fullscreen
4. See error (toolbar shows up on top of the fullscreen app)

**Expected behavior**
The toolbar should not show on fullscreen

**Screenshots**

Floorp fullscreen (F11)
![image](https://github.com/user-attachments/assets/94415a58-649f-44d4-8c73-fa8316323f17)

Youtube running in zen browser (firefox)
![image](https://github.com/user-attachments/assets/d14ac006-bb33-4211-8727-ddcdfe79036c)
(I tried both f11 mode and fullscreen youtube on microsoft edge but it works fine there)

MPV video player
![image](https://github.com/user-attachments/assets/c1188885-1765-4aea-bb3d-78d72ce66bca)

hsr
![image](https://github.com/user-attachments/assets/74faa8e4-6695-45ff-b89a-db0512e03cd8)

Steam big picture mode
![image](https://github.com/user-attachments/assets/47c5eb96-1504-4922-9b21-a2d00b083a4a)

cs2
![image](https://github.com/user-attachments/assets/564890ad-3f2c-4f92-925a-4bbb681dab73)

**Comment by eythaann** [comment]
partially fixed on: [24993d6](https://github.com/eythaann/Seelen-UI/commit/24993d67b5eda4e7fc27f5dcbd8527d50c0f2ba3)
