### ISSUE TITLE
[FEAT] Add "Ultrawide Vertical Stack" as a layout

### ISSUE THREAD

**Issue by Ryah** [eythaann/Seelen-UI#51]
**Is your feature request related to a problem? Please describe.**
I really like Seelen UI and prefer it over base Komorebi for it's extra functions and use of virtual desktops as workspaces, but I can't figure out how to add [Ultrawide Vertical Stack ](https://lgug2z.github.io/komorebi/example-configurations.html#ultrawide-vertical-stack) as a layout. I'm on a 32:9 monitor, so all of the other base layouts are practically useless to me due to them being very horizontally stretched. I tried checking out the json to maybe modify it myself, but I couldn't figure it out.

**Describe the solution you'd like**
Add the "Ultrawide Vertical Stack" from Komorabi as a selectable layout. If you could add it as a selectable option or explain how to add it myself, both would be amazing.

**Describe alternatives you've considered**
I tried other layouts and they are pretty much unusable for me on my monitor. 

**Additional context**
This is an absolutely amazing program and my preferred DE for Windows. Once this is added, it would be perfect for me.

**Comment by eythaann** [comment]
I made the implementation of custom layouts very easy on this app, just change the `growFactor` to match the best fit for you.
add this file at: `C:\Users\{your_user}\AppData\Roaming\com.seelen.seelen-ui\layouts`

```json
{
  "$schema": "https://raw.githubusercontent.com/eythaann/Seelen-UI/master/documentation/schemas/layout.schema.json",
  "info": {
    "displayName": "Ultrawide Vertical Stack",
    "author": "eythaann",
    "description": "Ryah's request for an ultrawide vertical stack"
  },
  "structure": {
    "type": "Horizontal",
    "children": [
      {
        "type": "Leaf",
        "growFactor": 1.5,
        "priority": 2
      },
      {
        "type": "Leaf",
        "growFactor": 1.5,
        "priority": 1
      },
      {
        "type": "Vertical",
        "priority": 3,
        "children": [
          {
            "type": "Leaf"
          },
          {
            "type": "Leaf"
          },
          {
            "type": "Leaf"
          },
          {
            "type": "Leaf"
          }
        ]
      }
    ]
  },
  "no_fallback_behavior": "Float"
}
```

you can see some others examples at: https://github.com/eythaann/Seelen-UI/tree/master/static/layouts
