### ISSUE TITLE
[FEAT] Solid Taskbar

### ISSUE THREAD

**Issue by LovelyLince** [eythaann/Seelen-UI#52]
Personally, I only want a highly customizable taskbar. I don't find it useful to separate the system tray onto its own toolbar, & I dislike the current implementation of the taskbar. I enabled the option to never hide the taskbar, but that causes it to always cover the window behind it. There's no point in this option if it stops me from clicking part of another app.

**Comment by eythaann** [comment]
![Seelen UI - Solid Taskbar Mode Enabled](https://github.com/user-attachments/assets/56623e4d-be2e-4104-bb0b-9489ed4fad68)

added on: 390fd865bab454930ffa9d5883db0c49de2038d1
