### ISSUE TITLE
[BUG] Notifications Not Displaying Slide Pop-Up

### ISSUE THREAD

**Issue by KiraiEEE** [eythaann/Seelen-UI#55]
**Description:**

- Notifications are not displaying the slide pop-up, making it easy to miss important alerts, as the notification count in the icon is not prominent enough.
- This issue also affects the use of tools like the Snipping Tool. Without the pop-up, it's difficult to notice and interact with notifications, such as clicking to edit a screenshot.

**Steps to Reproduce:**
- Gettings notification.
- Using Snipping Tool shortcut (Shift+Win+S).

**Expected Behavior:**
- Either allow the Windows system notifications or implement a custom notification system that ensures notifications are visible and actionable.

**Comment by eythaann** [comment]
partially fixed, iterations with notifications will be implemented on other ticket.
