### ISSUE TITLE
[BUG] UI Doesn't show on reboot

### ISSUE THREAD

**Issue by asislife20** [eythaann/Seelen-UI#57]
**Describe the bug**
The UI interface, or normal taskbar doesn't show up on reboot. In order to get the UI to open again I have to close both explorer.exe and seelen from task manager. Then reopen explorer in task manager and manually start seelen ui. The start on boot option in seelen is enabled 

**To Reproduce**
1. Power off or restart pc from start menu.
2. Power up pc
3. Seelen ui, or windows taskbar don't load.

**Expected behavior**

**Screenshots**

**Comment by rafliiar17** [comment]
taskbar and toolbar in my windows dont show up when restarting

blank
![Uploading image_2024-10-03_084635981.png…]()

**Comment by arsiavdiu** [comment]
Hey i downloaded the new version and i still get this problem. I had to manually put the app on the startup folder so that it can start directly after windows.

**Comment by eythaann** [comment]
try disabling and enabling again the auto start switch to remade the task. we use task scheduler for autostartup not startup folder/registry.
