### ISSUE TITLE
[BUG] Not work? Why?

### ISSUE THREAD

**Issue by P0etry-rain** [eythaann/Seelen-UI#58]
It doesn't work when I try to install the EXE.
(I wanted to report more details about the problem, but I couldn't. There is nothing here. I am sorry about that)
![PixPin_2024-08-29_09-55-54](https://github.com/user-attachments/assets/42719345-f3a3-44cc-85e6-2ab227774634)

**Comment by eythaann** [comment]
@P0etry-rain please, send me the log file on `C:\Users\{your user}\AppData\Local\com.seelen.seelen-ui\logs`

**Comment by P0etry-rain** [comment]
> @P0etry-rain please, send me the log file on `C:\Users\{your user}\AppData\Local\com.seelen.seelen-ui\logs`请送我的日志上的文件 `C:\Users\{your user}\AppData\Local\com.seelen.seelen-ui\logs`

I checked the log, and the log report is missing WebView2 runtime. I'm very sorry for submitting this meaningless issue, and I apologize for taking up your time.
😢
