### ISSUE TITLE
[BUG] Native Windows taskbar will not show up if hide automatically is on and an app is blocking the taskbar area (ex: on fullscreen)

### ISSUE THREAD

**Issue by Dadangdut33** [eythaann/Seelen-UI#59]
**Describe the bug**
I have been using only the toolbar because i actually like keeping the original taskbar from windows but like to keep it hidden to save space. But the problem is that when using Seelen UI and an application is on fullscreen or that its blocking the taskbar area, the taskbar will not show up on mouse hover. It seems that the taskbar gets behind the app. I have confirmed that this also only happen when using Seelen and I don't know why but this bug does not happen on my second monitor.

**To Reproduce**
1. Make windows taskbar automatically hide in the settings
2. Open Seelen UI
3. Fullscreen an app
4. Try to hover on the taskbar area
5. See error (taskbar will not show up)

**Expected behavior**
It should show up just like usual

**Screenshots**

https://github.com/user-attachments/assets/b24ba315-688e-400f-94db-f56799943db5

**Comment by eythaann** [comment]
hmm did you try restart the pc? or just restart `explorer.exe` from Task Manager?.

**Comment by Dadangdut33** [comment]
> hmm did you try restart the pc? or just restart `explorer.exe` from Task Manager?.

restarting explorer.exe seems to work but it would then remove the reserved space of the toolbar making windows go behind it just like in this picture: 

![image](https://github.com/user-attachments/assets/984a68eb-28d7-4bb9-9bd0-80ecc7f180b1)

Also, if after that i reload seelen the problem will happen again.

(i am still on [v1.9.11](https://github.com/eythaann/Seelen-UI/releases/tag/v1.9.11) btw because still waiting for the winget package update)

**Comment by eythaann** [comment]
hmm, let try to replicate it and I will check to fix this.

**Comment by eythaann** [comment]
related with #63

**Comment by eythaann** [comment]
I discovered that secondary shell (taskbar) are always on top, but the primary doesn't. why? Well microsoft bug, you can check that if you fullscreen the browser on the primary monitor the taskbar can no be showed but on the secondary monitor YES!? so this is a Windows bug. btw I thought this will be fixed on the fix for #63 I will close this issue as not planned but please check for #63.
