### ISSUE TITLE
[FEAT] Allow adding custom keybindings

### ISSUE THREAD

**Issue by asrma7** [eythaann/Seelen-UI#60]
**Is your feature request related to a problem? Please describe.**
The app does not allow adding custom keymaps. For example, there is no way I can define Alt + Q to quit the active window or Alt + Return to open Terminal.

**Describe the solution you'd like**
In the shortcut section having an "Add" button to define custom keymaps and documentation on Seelen Api to work with the system would be handy.

**Describe alternatives you've considered**
For now, I have settled with my custom AutoHotKey script to achieve some level of remaping. Here is the script if anyone needs it:
```
#Requires AutoHotkey v2.0
#SingleInstance Force
#NoTrayIcon

!Enter:: Run "wt"

!+b:: ; Alt + Shift + B to open chrome
{
    Run "Chrome"
}

!+f:: ; Alt + Shift + F to open firefox
{
    Run "Firefox"
}

!+r:: Reload ; Alt + Shift + R to Reload the script

!q::  ; Alt + Q to quit active window
{
    if WinGetTitle("A") == "Seelen Fancy Toolbar" || WinGetTitle("A") == "SeelenWeg" || WinGetTitle("A") == "Seelen Window Manager"
        return
    else
        Send "!{F4}"
}
```

**Comment by eythaann** [comment]
the `.ahk` files generated are written at `C:\Users\{user}\AppData\Local\com.seelen.seelen-ui`, you can use that files (I found a little bug about the path of the .lib.ahk, haha), btw this could be a guide to made customs `.ahk`

**Comment by eythaann** [comment]
now talking about the feature request, hmm I thought this could be a good feature but idk if it is really necessary, I also have my own .ahk files to open terminals, firefox, etc. So I do not think this feature is a requirement, but could be a plus, not for now but maybe in a future. so I will close this issue as not planned.
