### ISSUE TITLE
[FEAT] Custom Start Menu

### ISSUE THREAD

**Issue by Sobserius** [eythaann/Seelen-UI#62]
**The problem**
Built-in Start Menu (and not only) is kinda broken:

> You cant exit the Start Menu by pressing Start Module button again

> Start Menu often clips through the Taskbar/Dock

> If you dont have Taskbar/Dock enabled, the Start Menu pops out of nowhere

 And many other bugs that I know nothing about...

**The solution that I'd like**
Add a plugin (or maybe an option in Settings) that will add Custom Start Menu

**Comment by eythaann** [comment]
this is already planned on v2, see the incoming features on [readme](/readme.md)
