### ISSUE TITLE
[BUG] Toolbar & Multiple Monitors

### ISSUE THREAD

**Issue by RustyElbow** [eythaann/Seelen-UI#66]
When toolbar is enabled I can't interact with anything on my other monitor.

**Comment by eythaann** [comment]
wait what? can you share video example please?

**Comment by Raidenplays** [comment]
I have the same bug now too when it actually loads

**Comment by Raidenplays** [comment]
the only way to get stuff to work on the second screen is to alt f4 the top bar but doing that causes thew whole program to crash shortly after 
https://github.com/user-attachments/assets/dcb051dc-da03-4582-874e-0318fa72d99a

[Seelen UI.log](https://github.com/user-attachments/files/16818818/Seelen.UI.log)
