### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by elkhaligy** [eythaann/Seelen-UI#67]
Hi, the program is crashing after like 3 seconds, here's the log file
[Seelen UI.log](https://github.com/user-attachments/files/16817531/Seelen.UI.log)

**Comment by eythaann** [comment]
it looks like some value is null on reading UWP info, let me try a fix abut I'm no able to replicate this so you will have to test it.

**Comment by elkhaligy** [comment]
> it looks like some value is null on reading UWP info, let me try a fix abut I'm no able to replicate this so you will have to test it.

Ok

**Comment by elkhaligy** [comment]
Do you think it is because I uninstalled Edge? but I left webview

**Comment by eythaann** [comment]
you need edge, but the crash is caused by other issue.

**Comment by eythaann** [comment]
@elkhaligy tag me if the problem persist, but this in theory should be fixed on v1.10.1
