### ISSUE TITLE
[BUG] Toolbar/Dock and Explorer fullscreen

### ISSUE THREAD

**Issue by CalvinSmithDev** [eythaann/Seelen-UI#68]
**Describe the bug**
When Windows File Explorer is maximized, Toolbar and Dock don't appear on mouse at edge.

**To Reproduce**
1. Set Toolbar or Dock to 'On Overlap" hide.
2. Maximize Windows File Explorer
3. Toolbar and Dock do not appear when at edge of screen.

**Expected behavior**
Mouse at the edge should make toolbar or dock appear.

**Comment by eythaann** [comment]
this will be fixed on #63, this issue is also a problem related with z-orders and top most on seelen widgets.
