### ISSUE TITLE
[BUG] Crashes every time I launch it

### ISSUE THREAD

**Issue by Jacob-Tate** [eythaann/Seelen-UI#69]
**Describe the bug**
Faulting application name: seelen-ui.exe, version: 1.10.0.0, time stamp: 0x66d0ccdc
Faulting module name: seelen-ui.exe, version: 1.10.0.0, time stamp: 0x66d0ccdc
Exception code: 0xc0000409
Fault offset: 0x00000000012e1739
Faulting process id: 0x0x5E5C
Faulting application start time: 0x0x1DAFB0B973EA254
Faulting application path: C:\Program Files\Seelen\Seelen UI\seelen-ui.exe
Faulting module path: C:\Program Files\Seelen\Seelen UI\seelen-ui.exe
Report Id: 93a88c34-ea49-4260-b8ec-e3aa406fcb2e
Faulting package full name: 
Faulting package-relative application ID: 

**To Reproduce**
Launch the application

**Comment by Nicoolodion** [comment]
Yup got the same exact problem :/

**Comment by eythaann** [comment]
could you send me the log file at:  `C:\Users\{your user}\AppData\Local\com.seelen.seelen-ui\logs` please

**Comment by Nicoolodion** [comment]
Here is the log that it gives me. But I of course don't if the others got the same issue.
[Seelen UI.log](https://github.com/user-attachments/files/16822346/Seelen.UI.log)

**Comment by eythaann** [comment]
> Here is the log that it gives me. But I of course don't if the others got the same issue. [Seelen UI.log](https://github.com/user-attachments/files/16822346/Seelen.UI.log)

bro, did you delete powershell from your system?

**Comment by Nicoolodion** [comment]
> bro, did you delete powershell from your system?

I don't think so xD
Maybe a noob answer but I can still open it over the search function. Any other app also worked fine I guess?

**Comment by eythaann** [comment]
well the logs says that powershell doesn't exist haha lol

**Comment by Nicoolodion** [comment]
Okay thats... weird xD
Tried installing it even tho I think it never was uninstalled. Also tried a PC restart but every time the programm just sets my taskbar to autohide, shows me the UI for a few seconds and then closes itself...

**Comment by eythaann** [comment]
could you try open cmd and run `powershell`
![image](https://github.com/user-attachments/assets/b9a0d88f-01ac-434f-a831-f689cb41863f)

**Comment by Jacob-Tate** [comment]
[Seelen UI.log](https://github.com/user-attachments/files/16823066/Seelen.UI.log)

**Comment by Jacob-Tate** [comment]
I dont even get the UI just an instant crash

**Comment by eythaann** [comment]
@Jacob-Tate already fixed on v1.10.2

**Comment by eythaann** [comment]
same as #71

**Comment by Nicoolodion** [comment]
> could you try open cmd and run `powershell` ![image](https://private-user-

hm yeah it seems like I really haven't installed it somehow. It just gives me an error that nothing is found when trying that.
So, how can I install it again? xD

**Comment by Nicoolodion** [comment]
Okay finally got it installed
Works for me now :)

**Comment by Surajvmiskin** [comment]
> could you send me the log file at: `C:\Users\{your user}\AppData\Local\com.seelen.seelen-ui\logs` please


[Seelen UI.log](https://github.com/user-attachments/files/17935818/Seelen.UI.log)


mine also same one can you check the logs
