### ISSUE TITLE
[BUG] Seelen-UI crashing on first install

### ISSUE THREAD

**Issue by aless2003** [eythaann/Seelen-UI#71]
**Describe the bug**
So it's entirely possible I'm doing something wrong here, if so tell me about what I'm doing wrong please, but I've installed it through I believe all methods as far as I can tell and Seelen is crashing on all of them. It hides the taskbar then in the task manager you can see Seelen with lots of processes including a Crashpad process which I assume tells me it has crashed. (Or at least the desktop doesn't change whatsoever)

I've attached the logs in the hope they can help in any way.

**To Reproduce**
Install it and open it I guess

**Expected behavior**
It should show me a UI or the modified Desktop or something

[Seelen UI.log](https://github.com/user-attachments/files/16822644/Seelen.UI.log)

**Comment by eythaann** [comment]
test it again on v1.10.2 (it's been deployed)
