### ISSUE TITLE
[BUG] Pinned apps duplicating when dragged

### ISSUE THREAD

**Issue by dwr-studio** [eythaann/Seelen-UI#73]
**Describe the bug**
Pinned apps duplicating when dragged on second monitor.

**To Reproduce**
1. Have two monitors
2. Drag pinned apps
3. Enjoy the magic

**Screenshots**

https://github.com/user-attachments/assets/2e313ae6-ea2d-43e9-b651-d0816a00cc66

**Comment by eythaann** [comment]
LOL

**Comment by hexadecimal233** [comment]
#37 😱

**Comment by eythaann** [comment]
I try it, but I can not replicate it.

**Comment by eythaann** [comment]
I made a preventive commit, but idk if that will fix this, how is unreplicable and not is the first time this ticket was reported, I will let open this ticket until someone comments how replicate this bug exactly.

**Comment by anventia** [comment]
Similar problem for me, however:
- 1 monitor
- Only my Task Manager icon duplicates.

**Comment by re1e4se** [comment]
I have the same issue, how to reproduce:
1. Have 2 monitors
2. Pin an app to the dock from the primary monitor
3. Drag the newly pinned app from the primary monitor

After that, it duplicates itself on the secondary monitor.

**Comment by eythaann** [comment]
Replicable: open two or more app as admin, while running seelen without admin rights, next move some items, and that's is: magic
