### ISSUE TITLE
[BUG] PWA Apps

### ISSUE THREAD

**Issue by elkhaligy** [eythaann/Seelen-UI#77]
**Describe the bug**
PWA apps appears as a tab in the browser, tested browsers: Edge

**To Reproduce**
1. Open any PWA app

**Expected behavior**
Each PWA app should have its own icon and instance in the taskbar

**Comment by eythaann** [comment]
![image](https://github.com/user-attachments/assets/86311e97-8837-4e5a-9b01-a62588dc0411)

only tested with edge

**Comment by eythaann** [comment]
![Seelen UI manage pwa applications](https://github.com/user-attachments/assets/249b4f29-1a1c-4300-8850-4b0d8420e3b9)
only tested with pwa based on edge, like mstore pwa or pwa added via edge browser.
