### ISSUE TITLE
[BUG] Fancy Toolbar doesn't play nice with wallpaper engine. 🐛🐛🐛

### ISSUE THREAD

**Issue by madhav-bhartia** [eythaann/Seelen-UI#79]
**Description**
Use the fancy toolbar with the wallpaper engine running, and it'll go to the desktop (like it will [kinda] minimize the engine.)

**Steps to reproduce the behavior:**
1. Have wallpaper engine running.
2. Click on 'anything in the fancy toolbar'
4. Voila! See error.

**Expected behavior**
To let wallpaper engine run in background (as it would without the [glitched] fancy toolbar.

**Screenshots**
(BTW the "before" wallpaper is animated...)
Before:
![image](https://github.com/user-attachments/assets/7a291fed-11dd-425d-ada0-c6a08072545d)
After:
![image](https://github.com/user-attachments/assets/4d79df34-6978-49e4-bd74-6a2f695167d7)

**Comment by eythaann** [comment]
the problem here is that the wallpaper engine detects the UI as a Fullscreen app, maybe the app has a way to add a white list of apps?, for now there's nothing I can do about this.
