### ISSUE TITLE
[BUG] Can't run after installing from store

### ISSUE THREAD

**Issue by markox92** [eythaann/Seelen-UI#8]
**Describe the bug**
Can't run app after installing from store

![Screenshot 2024-04-14 205705](https://github.com/eythaann/Seelen-UI/assets/159203552/c7bbf47e-d80a-43e3-bf3c-2681988c4796)

**Comment by eythaann** [comment]
@markox92 Hi I already know about this and is already fixed but updates to the Store takes around 3 or more days on be uploaded to the store. This error doesn't appear if you run the app as admin.
