### ISSUE TITLE
[BUG] Start Menu always popups up on main monitor.

### ISSUE THREAD

**Issue by PsycloneTM** [eythaann/Seelen-UI#80]
**Describe the bug**
When going to open the start menu on any other monitor but your main monitor it will open on the main monitor instead of the one you click the start button on.

**To Reproduce**
1. Go to a second monitor.
2. Click on the start button

**Expected behavior**
When clicking on the start button it should open the start menu on the monitor you are currently open.

**Screenshots**
![image](https://github.com/user-attachments/assets/d2337b41-ad6a-4e4a-affe-0528ebf6fa45)

**Comment by eythaann** [comment]
hmm this is how windows works tho?

**Comment by HeasHeartfire** [comment]
> hmm this is how windows works tho?

That's how the windows key on the keyboard works, however the button on the taskbar does indeed open the start menu on the current monitor.

**Comment by eythaann** [comment]
hmmm, btw this will work as currently is, I will not implement a fix for this because how is working the start menu just simulate a Windows key, also I'm currently implementing a custom App Launcher so the native Start Menu doesn't need fully compatibility.
