### ISSUE TITLE
[BUG] Dock and Toolbar not restoring on close.

### ISSUE THREAD

**Issue by PsycloneTM** [eythaann/Seelen-UI#81]
**Describe the bug**
When opening an application that covers the dock and toolbar sometimes after closing the application they dont unhide.

**To Reproduce**
1. Turn on hide on overlay for dock and toolbar.
2. Open an Nividia controls Alt + Z.
3. Close it.

**Expected behavior**
Upon closing of the application it should unhide the dock and toolbar.

**Screenshots**
https://github.com/user-attachments/assets/5bfc516e-d533-4642-9b77-809d7872f3f3

**Comment by eythaann** [comment]
@PsycloneTM could you check if this was fixed on v2 beta 4? if yes, please close this issue. :D

**Comment by PsycloneTM** [comment]
@eythaann Seems to be fixed!
