### ISSUE TITLE
its not working on system app ex: file explorer

### ISSUE THREAD

**Issue by aadeshpall** [eythaann/Seelen-UI#82]
**Describe the bug**
i use dock and toolbar in (auto hide: on-overlap)
its working for 3rd party apps like chrome etc.
but, its not working for system apps like setting, file explorer etc.

**To Reproduce**
1. Go to 'setting or file explorer' open full screen
2. Click on 'close it the again open setting or file explorer'
3. Scroll down to 'then the dock will not pop'
5. (auto hide: on-overlap) both dock and toolbar

I think the problem is:
when you open the file explorer or setting the "thin line" on top will not fill by the app bcoz of the toolbar
then the sys app pushed down by little bit that's why the dock won't coming up my curser never reached the bottom of screen

**Screenshots**
![Screenshot (492)](https://github.com/user-attachments/assets/764754b4-37cc-46cd-918c-2fdadd3cce93)
![Screenshot (491)](https://github.com/user-attachments/assets/d6d942bc-a1f4-4904-9cb2-27c00a3ca000)

**Comment by eythaann** [comment]
duplicated of #68
