### ISSUE TITLE
[BUG] Edge tabs are open in the file explorer

### ISSUE THREAD

**Issue by elkhaligy** [eythaann/Seelen-UI#83]
**Describe the bug**
Strangely I found that edge tabs exist in the file explorer previews, like if they were instances of the explorer.exe , probably happens only with edge.

**To Reproduce**
1. Open Edge, and then some tabs
2. Hover on the explorer in the taskbar

**Screenshots**
![image](https://github.com/user-attachments/assets/6fb3e463-557b-4dd3-b3f2-6c6529e77f70)

**Comment by Gn3po4g** [comment]
+1
