### ISSUE TITLE
[FEAT] More funcs

### ISSUE THREAD

**Issue by vanja-san** [eythaann/Seelen-UI#86]
Most likely, something already exists as an idea, but I was too lazy to look for it, sorry ☺️

`In short "More customization is needed"`

- [x] Change (enable/disable) icons in toolbar without having to create a separate theme
  - for example, add a context menu when right-clicking on an icon
- ❓ Pin individual applications to taskbar (e.g. Aimp) as a media player (if only it is possible and there is time and energy for it)
  - and of course more customization (like changing length, size, etc.)
- [x] More context menu items when right-clicking on taskbar
  - e.g. "Add Item" (with a separate popup window for adding a shortcut)
- [x] Scalable SeelenUI settings window
- ❌ Panels background blur (windows 11 is nowhere without it)
  - just a toggler in settings

But first priority is to fix problems at hand. Have a good mood!

**Comment by eythaann** [comment]
Resizable Settings done on: 3ae10b6ff50383fbc4d5df34ed7d3b19bdb108fd

**Comment by vanja-san** [comment]
@eythaann does the cross mean it's not planned (don't need)? It's going to be sad.

**Comment by eythaann** [comment]
stylish is a feature that should be done via themes, and not via settings, only accessibility like sizes or main styles like the dock position, should be added via config.

**Comment by vanja-san** [comment]
@eythaann Ahhh, well, that's logical, the question is settled. 🙂‍↕️

**Comment by eythaann** [comment]
currently on v2 now you can just drag and drop files/app/folders to the dock to pin them.
