### ISSUE TITLE
[FEAT] Boot according to options:  auto_hide_taskbar load_uwp_apps create_window

### ISSUE THREAD

**Issue by mystery4f** [eythaann/Seelen-UI#9]
Boot according to options:
-  auto_hide_taskbar
- load_uwp_apps create_window

**Comment by eythaann** [comment]
Hmm the loading of uwp apps is necessary for the correct behavior of the dock/taskbar so this should be no triggered by the user.

For the auto_hide_taskbar yes, I go to add a option to toggle it :D

**Comment by eythaann** [comment]
Auto Hide Behavior added on: [7ec7d77](https://github.com/eythaann/Seelen-UI/commit/7ec7d7777b3422d2e9de571d3e2b16951f1823f5)
