### ISSUE TITLE
[BUG] Taskbar Pinned Icons Reset to Tray After Closing Seelin UI.

### ISSUE THREAD

**Issue by KiraiEEE** [eythaann/Seelen-UI#90]
**Description:** When I close the Seelin UI, all the taskbar icons that are pinned directly to the taskbar (not hidden inside the tray arrow) are automatically moved into the tray area. This unexpected behavior causes the icons to reset, forcing me to **manually** drag them back to the taskbar each time I close the UI.

**Steps to Reproduce:**
Pin icons to the taskbar (make sure they are not hidden in the tray arrow).
Open Seelin UI.
Close Seelin UI.
Observe that the pinned icons are moved to the tray area.

**Expected Behavior:** Pinned icons should remain in the taskbar and not be moved into the tray area after closing the Seelin UI.

**Comment by eythaann** [comment]
This is intended, tray icons should be all in the overflow box to be used correctly on the tray module on toolbar.

**Comment by KiraiEEE** [comment]
> This is intended, tray icons should be all in the overflow box to be used correctly on the tray module on toolbar.

i mean the windows system tray icons not the seelin UI one

**Comment by eythaann** [comment]
> > This is intended, tray icons should be all in the overflow box to be used correctly on the tray module on toolbar.
> 
> i mean the windows system tray icons not the seelin UI one

yeah, the tray icons is not a api that can be used by other apps, it is a explorer.exe feature, not a System feature so on Seelen we map the try overflow window to have Tray Icons working on the app. call it a Trick

**Comment by KiraiEEE** [comment]
got it but manually rearranging icons each time I run and close SeelinUI is really frustrating. i wish there was a better Trick

**Comment by KiraiEEE** [comment]
> > > This is intended, tray icons should be all in the overflow box to be used correctly on the tray module on toolbar.
> > 
> > 
> > i mean the windows system tray icons not the seelin UI one
> 
> yeah, the tray icons is not a api that can be used by other apps, it is a explorer.exe feature, not a System feature so on Seelen we map the try overflow window to have Tray Icons working on the app. call it a Trick

got it but manually rearranging icons each time I run and close SeelinUI is really frustrating. i wish there was a better Trick
