### ISSUE TITLE
[BUG] Hovering Mouse on the Dock bar, its not loading

### ISSUE THREAD

**Issue by hsarode1244** [eythaann/Seelen-UI#93]
**Describe the bug**
I have set the Dock bar on the TOP screen. Whenever I tried to hover on it, its sometimes not loading, we need to hover mulitple times to load it and then will be able to click on running application window.

**To Reproduce**
1. Just set Dock bar on TOP with Auto-hide setting and try to hover on it by keeping multiple applications running in windows.
2. This behavior is seen on Windows 11 ( version 23H2 ) Build 22631.4037

**Expected behavior**
Whenever we hover mouse, it should load the Dock bar promptly.

**Feature Request**
Can we have dedicated shortcut button, to load the Dock bar anytime when we press it ( With Autohide flag enabled case ). **Example**: By default Windows Start Menu is hidden and whenever we click "Windows Symbol Button" on keyboard, it open up Start menu and again auto hide itself.

**Comment by eythaann** [comment]
I thought this was already fixed on the betas of v2.0, just try it to close this ticket.

**Comment by eythaann** [comment]
btw, yes the dock and toolbar should be shown on the win key pressed

**Comment by eythaann** [comment]
I just check this, and yes this is already fixed and working on v2.0

**Comment by hsarode1244** [comment]
> btw, yes the dock and toolbar should be shown on the win key pressed

This win key pressing does not auto-load the dock bar. Thats the issue I am facing, is there any dedicated shortcut key we can assign in newer version releases v2.0?

**Comment by eythaann** [comment]
on v2 when pressing Win key dock and toolbar are shown.
