### ISSUE TITLE
[BUG] Clock on toolbar is behind real-time

### ISSUE THREAD

**Issue by 45i** [eythaann/Seelen-UI#94]
**Describe the bug**
The clock on the toolbar is behind the real time, precisely by 40 seconds (for Americans, that's roughly the time taken to consume four hamburgers [ you're welcome :) ])

**To Reproduce**
1. Get hold of a working clock, preferably digital
2. Look at the time
3. Look at your monitor
4. Locate the toolbar
5. Look at the time and compare it with the time on your watch
 
**Expected behavior**
The two times should be the same

**Comment by eythaann** [comment]
#97 now you can easily set date format if you add `ss` to your date format that means `seconds` the date will be updated each second instead each minute, this in case you need precition. otherway the date will be updated each 60 seconds (1 minute) after been created the toolbar.

**Comment by ButcherZV** [comment]
yeah, i have that same bug
