### ISSUE TITLE
[BUG] Cannot open system tray

### ISSUE THREAD

**Issue by PhantomPixel-0418** [eythaann/Seelen-UI#95]
**Error in description**
Tapping on the system tray does not respond

**Reproduced**
Steps to reproduce the behavior
1. Tap “Open System Tray”
2. View the error

**Expected behavior**
Click and an icon is displayed

**Screenshot**
![image](https://github.com/user-attachments/assets/3e375a72-2e81-4f6a-b571-dc6eb8766e82)

**Comment by eythaann** [comment]
@PhantomPixel-0418 please try v2 beta.10 and tell me if now is working for you please, if not, reopen this issue.

**Comment by PhantomPixel-0418** [comment]
**Please reopen this issue, the problem is still not solved!**
