### ISSUE TITLE
[BUG] Middle Mouse Click to close app does not work on dock

### ISSUE THREAD

**Issue by 45i** [eythaann/Seelen-UI#96]
> im back babyyyyy

**Describe the bug**
Middle Mouse Click to close an app does not work on the dock app preview 

**To Reproduce**
1. Go to the dock
2. Hover over any app
3. middle click on the app or the preview of the app

**Expected behavior**
ITS SUPPOSED TO CLOSE THE APP OMFG

**Comment by eythaann** [comment]
done on: e4195c7a8726c4b51e53a832592b47924a360f9c
