### ISSUE TITLE
[FEAT] Support other Date & Time Formats

### ISSUE THREAD

**Issue by ronniehartmann** [eythaann/Seelen-UI#97]
**Is your feature request related to a problem? Please describe.**
Currently the date and time is shown as "Wed 18 Sep, 05:17 PM". I haven't found an option, where you can change the format.

**Describe the solution you'd like**
It would be nice if there was a setting to change the format or if it would be applied automatically from the windows settings. I'd like to have the time to be shown as "17:18". 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by eythaann** [comment]
currently, the date format is part of the placeholder, but yeah maybe I should add a option in the UI to allow normal users easily change the format date.
