### ISSUE TITLE
[BUG] Media Module has completely lost its mind

### ISSUE THREAD

**Issue by 45i** [eythaann/Seelen-UI#98]
**Describe the bug**
Media Module will occasionally not update. The controls work but the cover art and song name do not update on both dock media module and media player in the volume flyout

**Expected behavior**
its supposed to sync in realtime

**Screenshots**
![image](https://github.com/user-attachments/assets/f41d52b3-6d42-4ce6-9af3-3c8692ad2caf)
![image](https://github.com/user-attachments/assets/06cb1a2d-4e53-4d97-ba18-0d7aa7c84957)

**Comment by eythaann** [comment]
this should be already fixed, try it again
