### ISSUE TITLE
[BUG] File explorer!

### ISSUE THREAD

**Issue by Erforias** [eythaann/Seelen-UI#99]
i open GitHub on edge browser and it shows in file explorer page

![Screenshot 2024-09-18 193921](https://github.com/user-attachments/assets/a24d6989-b370-451e-aa93-8dae1248245c)

and can you add transparent effect?:)

![image](https://github.com/user-attachments/assets/aeef650e-9dc7-48b9-b2c4-f4a1cb6ba259)

like my start menu.
*add hide on taskbar button when right click on apps.
tnx for this beautiful app :D.

**Comment by eythaann** [comment]
duplicated of #83, and the blur effect its a really complicated thing taking in care the Themes and user customizations, the blur effect on windows can be only applied to the entire window and not on specific parts.
